const liveBrowserProfileSetupEnglish = [
  "Your organization may block sign-in to tenants other than your work tenant. To access the training environment, you **must** use a browser profile that is **not signed into your work account**. Follow the steps below.",
  "",
  "---",
  "",
  "## Option 1: Create a New Edge Profile *(Recommended)*",
  "",
  "A separate profile keeps your training session alive across browser restarts and won't interfere with your work profile.",
  "",
  "### Step 1: Create the profile",
  "",
  "1. Open **Microsoft Edge**.",
  "2. Click your **profile icon** in the top-right corner of the browser.",
  "3. Click **Set up a new profile** (at the bottom of the profile flyout).",
  "4. When prompted to choose a profile type, click **Work or school**. (Do **not** choose Personal — the training tenant is an organizational account.)",
  "5. Click **Start without your data**.",
  "6. Click **Confirm and start browsing**.",
  "7. **Do NOT sign in** with any account. Skip or dismiss any sign-in prompts.",
  "",
  "> 📖 **Official docs:** [Sign in and create multiple profiles in Microsoft Edge](https://support.microsoft.com/en-us/topic/sign-in-and-create-multiple-profiles-in-microsoft-edge-df94e622-2061-49ae-ad1d-6f0e43ce6435)",
  "",
  "### Step 2: Confirm you are NOT signed in",
  "",
  "Before navigating to the jumpstart workshop tenant, verify the profile is clean:",
  "",
  "1. In your **new profile window**, click the **profile icon** in the top-right corner.",
  "2. It should show **\"Sign in to sync data\"** or a generic person silhouette — **not** your name or work email.",
  "3. Navigate to `edge://settings/profiles` and confirm no account is listed under **\"Microsoft account\"** or **\"Work or school account\"**.",
  "4. As a final check, go to [**portal.microsoft.com**](https://portal.microsoft.com/). You should see a generic sign-in page — **not** be auto-signed-in to your work tenant.",
  "",
  "If you see your work identity anywhere, you are in the wrong profile. Switch to the new profile you just created.",
  "",
  "### Step 3: Get your training account and access the labs",
  "",
  "1. Use the **user name and password provided by your instructor** when prompted.",
  "2. The instructor will provide you with training credentials (username and password).",
  "3. Go to [**portal.microsoft.com**](https://portal.microsoft.com/) and log in using the credentials provided by the agent.",
  "4. Go to the [**AI Agent Jumpstart — Microsoft Copilot Agents Labs**](https://aka.ms/AgentJumpStart/) to access the labs. **Make sure you are in the labs specific to your workshop.**",
  "",
  "---",
  "",
  "## Option 2: InPrivate Browsing in Edge *(Fallback)*",
  "",
  "> ⚠️ **Warning:** InPrivate sessions do not persist. If you **close the InPrivate window**, you will be **immediately signed out** of the training tenant and will need to sign in again. All tabs, session state, and unsaved work in the browser will be lost. Use this only if you cannot create a new profile.",
  "",
  "1. Open **Microsoft Edge**.",
  "2. Press **Ctrl + Shift + N**, or click **Settings and more (⋯)** → **New InPrivate window**.",
  "3. A dark-themed window opens with the **\"InPrivate\"** label visible in the top-left corner.",
  "4. Navigate to the training tenant URL and sign in with your **training credentials**.",
  "5. **Do not close this window** for the duration of the training session.",
  "",
  "> 📖 **Official docs:** [Browse InPrivate in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/browse-inprivate-in-microsoft-edge-e6f47704-340c-7d4f-b00d-d0cf35aa1fcc)",
  "",
  "---",
  "",
  "## Other Browsers — Profile Setup Guides",
  "",
  "If you are not using Microsoft Edge, use these official guides to create a separate browser profile:",
  "",
  "| Browser | Guide |",
  "| --- | --- |",
  "| **Google Chrome** | [Create Chrome browser profiles](https://support.google.com/chrome/answer/2364824) |",
  "| **Mozilla Firefox** | [Profile Manager — Create, remove, or switch Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) |",
].join('\n')

const liveBrowserProfileSetupVietnamese = [
  "Tổ chức của bạn có thể chặn việc đăng nhập vào các tenant khác với tenant công việc. Để truy cập môi trường đào tạo, bạn **phải** sử dụng một hồ sơ trình duyệt **chưa đăng nhập vào tài khoản công việc**. Hãy làm theo các bước dưới đây.",
  "",
  "---",
  "",
  "## Lựa chọn 1: Tạo hồ sơ Edge mới *(Khuyến nghị)*",
  "",
  "Hồ sơ riêng giúp duy trì phiên đào tạo sau khi khởi động lại trình duyệt và không ảnh hưởng đến hồ sơ công việc của bạn.",
  "",
  "### Bước 1: Tạo hồ sơ",
  "",
  "1. Mở **Microsoft Edge**.",
  "2. Bấm vào **biểu tượng hồ sơ** ở góc trên bên phải của trình duyệt.",
  "3. Bấm **Set up a new profile** (ở cuối bảng hồ sơ bật ra).",
  "4. Khi được yêu cầu chọn loại hồ sơ, bấm **Work or school**. (**Không** chọn Personal — tenant đào tạo là tài khoản của tổ chức.)",
  "5. Bấm **Start without your data**.",
  "6. Bấm **Confirm and start browsing**.",
  "7. **KHÔNG đăng nhập** bằng bất kỳ tài khoản nào. Bỏ qua hoặc đóng mọi lời nhắc đăng nhập.",
  "",
  "> 📖 **Tài liệu chính thức:** [Sign in and create multiple profiles in Microsoft Edge](https://support.microsoft.com/en-us/topic/sign-in-and-create-multiple-profiles-in-microsoft-edge-df94e622-2061-49ae-ad1d-6f0e43ce6435)",
  "",
  "### Bước 2: Xác nhận bạn CHƯA đăng nhập",
  "",
  "Trước khi chuyển đến tenant của hội thảo jumpstart, hãy xác nhận hồ sơ đang ở trạng thái sạch:",
  "",
  "1. Trong **cửa sổ hồ sơ mới**, bấm vào **biểu tượng hồ sơ** ở góc trên bên phải.",
  "2. Hồ sơ phải hiển thị **\"Sign in to sync data\"** hoặc hình người mặc định — **không phải** tên hay email công việc của bạn.",
  "3. Truy cập `edge://settings/profiles` và xác nhận không có tài khoản nào trong **\"Microsoft account\"** hoặc **\"Work or school account\"**.",
  "4. Để kiểm tra lần cuối, hãy truy cập [**portal.microsoft.com**](https://portal.microsoft.com/). Bạn phải thấy trang đăng nhập chung — **không** được tự động đăng nhập vào tenant công việc.",
  "",
  "Nếu thấy danh tính công việc của mình ở bất kỳ đâu, bạn đang dùng sai hồ sơ. Hãy chuyển sang hồ sơ mới vừa tạo.",
  "",
  "### Bước 3: Nhận tài khoản đào tạo và truy cập các bài thực hành",
  "",
  "1. Khi được nhắc, hãy dùng **tên người dùng và mật khẩu do giảng viên cung cấp**.",
  "2. Giảng viên sẽ cung cấp thông tin đăng nhập đào tạo (tên người dùng và mật khẩu).",
  "3. Truy cập [**portal.microsoft.com**](https://portal.microsoft.com/) và đăng nhập bằng thông tin do Agent cung cấp.",
  "4. Truy cập [**AI Agent Jumpstart — Microsoft Copilot Agents Labs**](https://aka.ms/AgentJumpStart/) để mở các bài thực hành. **Hãy chắc chắn rằng bạn đang ở đúng bộ bài thực hành dành cho hội thảo của mình.**",
  "",
  "---",
  "",
  "## Lựa chọn 2: Duyệt InPrivate trong Edge *(Phương án dự phòng)*",
  "",
  "> ⚠️ **Cảnh báo:** Phiên InPrivate không được duy trì. Nếu bạn **đóng cửa sổ InPrivate**, bạn sẽ **ngay lập tức bị đăng xuất** khỏi tenant đào tạo và phải đăng nhập lại. Tất cả tab, trạng thái phiên và công việc chưa lưu trong trình duyệt sẽ bị mất. Chỉ dùng cách này khi bạn không thể tạo hồ sơ mới.",
  "",
  "1. Mở **Microsoft Edge**.",
  "2. Nhấn **Ctrl + Shift + N** hoặc bấm **Settings and more (⋯)** → **New InPrivate window**.",
  "3. Một cửa sổ giao diện tối sẽ mở ra với nhãn **\"InPrivate\"** ở góc trên bên trái.",
  "4. Truy cập URL của tenant đào tạo và đăng nhập bằng **thông tin đăng nhập đào tạo**.",
  "5. **Không đóng cửa sổ này** trong suốt phiên đào tạo.",
  "",
  "> 📖 **Tài liệu chính thức:** [Browse InPrivate in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/browse-inprivate-in-microsoft-edge-e6f47704-340c-7d4f-b00d-d0cf35aa1fcc)",
  "",
  "---",
  "",
  "## Trình duyệt khác — Hướng dẫn thiết lập hồ sơ",
  "",
  "Nếu không dùng Microsoft Edge, hãy làm theo các hướng dẫn chính thức sau để tạo hồ sơ trình duyệt riêng:",
  "",
  "| Trình duyệt | Hướng dẫn |",
  "| --- | --- |",
  "| **Google Chrome** | [Create Chrome browser profiles](https://support.google.com/chrome/answer/2364824) |",
  "| **Mozilla Firefox** | [Profile Manager — Create, remove, or switch Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) |",
].join('\n')

const bundledBrowserProfileSetupEnglish = [
  "Your organization may block sign-in to tenants other than your work tenant. To access the training environment, you **must** use a browser profile that is **not signed into your work account**. Follow the steps below.",
  "",
  "---",
  "",
  "## Option 1: Create a New Edge Profile *(Recommended)*",
  "",
  "A separate profile keeps your training session alive across browser restarts and won't interfere with your work profile.",
  "",
  "### Step 1: Create the profile",
  "",
  "1. Open **Microsoft Edge**.",
  "2. Click your **profile icon** in the top-right corner of the browser.",
  "3. Click **Set up a new profile** (at the bottom of the profile flyout).",
  "4. When prompted to choose a profile type, click **Work or school**. (Do **not** choose Personal — the training tenant is an organizational account.)",
  "5. Click **Start without your data**.",
  "6. Click **Confirm and start browsing**.",
  "7. **Do NOT sign in** with any account. Skip or dismiss any sign-in prompts.",
  "",
  "> 📖 **Official docs:** [Sign in and create multiple profiles in Microsoft Edge](https://support.microsoft.com/en-us/topic/sign-in-and-create-multiple-profiles-in-microsoft-edge-df94e622-2061-49ae-ad1d-6f0e43ce6435)",
  "",
  "### Step 2: Confirm you are NOT signed in",
  "",
  "Before navigating to the training tenant, verify the profile is clean:",
  "",
  "1. In your **new profile window**, click the **profile icon** in the top-right corner.",
  "2. It should show **\"Sign in to sync data\"** or a generic person silhouette — **not** your name or work email.",
  "3. Navigate to `edge://settings/profiles` and confirm no account is listed under **\"Microsoft account\"** or **\"Work or school account\"**.",
  "4. As a final check, go to [**portal.microsoft.com**](https://portal.microsoft.com/). You should see a generic sign-in page — **not** be auto-signed-in to your work tenant.",
  "",
  "If you see your work identity anywhere, you are in the wrong profile. Switch to the new profile you just created.",
  "",
  "### Step 3: Get your training account and access the labs",
  "",
  "1. In your **new, unsigned-in profile**, go to [**Microsoft Copilot Studio Training**](https://aka.ms/MCSWorkshopAgent/) and chat with the training agent to get an account.",
  "2. Use the **code provided by your instructor** when prompted.",
  "3. The agent will provide you with training credentials (username and password).",
  "4. Go to [**portal.microsoft.com**](https://portal.microsoft.com/) and log in using the credentials provided by the agent.",
  "5. Go to the [**Architecture Bootcamp — Microsoft Copilot Agents Labs**](https://aka.ms/MCSWorkshopAgent/) to access the labs. **Make sure you are in the labs specific to your bootcamp.**",
  "",
  "---",
  "",
  "## Option 2: InPrivate Browsing in Edge *(Fallback)*",
  "",
  "> ⚠️ **Warning:** InPrivate sessions do not persist. If you **close the InPrivate window**, you will be **immediately signed out** of the training tenant and will need to sign in again. All tabs, session state, and unsaved work in the browser will be lost. Use this only if you cannot create a new profile.",
  "",
  "1. Open **Microsoft Edge**.",
  "2. Press **Ctrl + Shift + N**, or click **Settings and more (⋯)** → **New InPrivate window**.",
  "3. A dark-themed window opens with the **\"InPrivate\"** label visible in the top-left corner.",
  "4. Navigate to the training tenant URL and sign in with your **training credentials**.",
  "5. **Do not close this window** for the duration of the training session.",
  "",
  "> 📖 **Official docs:** [Browse InPrivate in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/browse-inprivate-in-microsoft-edge-e6f47704-340c-7d4f-b00d-d0cf35aa1fcc)",
  "",
  "---",
  "",
  "## Other Browsers — Profile Setup Guides",
  "",
  "If you are not using Microsoft Edge, use these official guides to create a separate browser profile:",
  "",
  "| Browser | Guide |",
  "| --- | --- |",
  "| **Google Chrome** | [Create Chrome browser profiles](https://support.google.com/chrome/answer/2364824) |",
  "| **Mozilla Firefox** | [Profile Manager — Create, remove, or switch Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) |",
  "",
  "The same principle applies: create a new profile, **do not sign in** with your work account, then navigate to the training tenant URL.",
].join('\n')

const bundledBrowserProfileSetupVietnamese = [
  "Tổ chức của bạn có thể chặn việc đăng nhập vào các tenant khác với tenant công việc. Để truy cập môi trường đào tạo, bạn **phải** sử dụng một hồ sơ trình duyệt **chưa đăng nhập vào tài khoản công việc**. Hãy làm theo các bước dưới đây.",
  "",
  "---",
  "",
  "## Lựa chọn 1: Tạo hồ sơ Edge mới *(Khuyến nghị)*",
  "",
  "Hồ sơ riêng giúp duy trì phiên đào tạo sau khi khởi động lại trình duyệt và không ảnh hưởng đến hồ sơ công việc của bạn.",
  "",
  "### Bước 1: Tạo hồ sơ",
  "",
  "1. Mở **Microsoft Edge**.",
  "2. Bấm vào **biểu tượng hồ sơ** ở góc trên bên phải của trình duyệt.",
  "3. Bấm **Set up a new profile** (ở cuối bảng hồ sơ bật ra).",
  "4. Khi được yêu cầu chọn loại hồ sơ, bấm **Work or school**. (**Không** chọn Personal — tenant đào tạo là tài khoản của tổ chức.)",
  "5. Bấm **Start without your data**.",
  "6. Bấm **Confirm and start browsing**.",
  "7. **KHÔNG đăng nhập** bằng bất kỳ tài khoản nào. Bỏ qua hoặc đóng mọi lời nhắc đăng nhập.",
  "",
  "> 📖 **Tài liệu chính thức:** [Sign in and create multiple profiles in Microsoft Edge](https://support.microsoft.com/en-us/topic/sign-in-and-create-multiple-profiles-in-microsoft-edge-df94e622-2061-49ae-ad1d-6f0e43ce6435)",
  "",
  "### Bước 2: Xác nhận bạn CHƯA đăng nhập",
  "",
  "Trước khi chuyển đến tenant đào tạo, hãy xác nhận hồ sơ đang ở trạng thái sạch:",
  "",
  "1. Trong **cửa sổ hồ sơ mới**, bấm vào **biểu tượng hồ sơ** ở góc trên bên phải.",
  "2. Hồ sơ phải hiển thị **\"Sign in to sync data\"** hoặc hình người mặc định — **không phải** tên hay email công việc của bạn.",
  "3. Truy cập `edge://settings/profiles` và xác nhận không có tài khoản nào trong **\"Microsoft account\"** hoặc **\"Work or school account\"**.",
  "4. Để kiểm tra lần cuối, hãy truy cập [**portal.microsoft.com**](https://portal.microsoft.com/). Bạn phải thấy trang đăng nhập chung — **không** được tự động đăng nhập vào tenant công việc.",
  "",
  "Nếu thấy danh tính công việc của mình ở bất kỳ đâu, bạn đang dùng sai hồ sơ. Hãy chuyển sang hồ sơ mới vừa tạo.",
  "",
  "### Bước 3: Nhận tài khoản đào tạo và truy cập các bài thực hành",
  "",
  "1. Trong **hồ sơ mới chưa đăng nhập**, truy cập [**Microsoft Copilot Studio Training**](https://aka.ms/MCSWorkshopAgent/) và trò chuyện với Agent đào tạo để nhận tài khoản.",
  "2. Khi được nhắc, hãy dùng **mã do giảng viên cung cấp**.",
  "3. Agent sẽ cung cấp thông tin đăng nhập đào tạo (tên người dùng và mật khẩu).",
  "4. Truy cập [**portal.microsoft.com**](https://portal.microsoft.com/) và đăng nhập bằng thông tin do Agent cung cấp.",
  "5. Truy cập [**Architecture Bootcamp — Microsoft Copilot Agents Labs**](https://aka.ms/MCSWorkshopAgent/) để mở các bài thực hành. **Hãy chắc chắn rằng bạn đang ở đúng bộ bài thực hành dành cho bootcamp của mình.**",
  "",
  "---",
  "",
  "## Lựa chọn 2: Duyệt InPrivate trong Edge *(Phương án dự phòng)*",
  "",
  "> ⚠️ **Cảnh báo:** Phiên InPrivate không được duy trì. Nếu bạn **đóng cửa sổ InPrivate**, bạn sẽ **ngay lập tức bị đăng xuất** khỏi tenant đào tạo và phải đăng nhập lại. Tất cả tab, trạng thái phiên và công việc chưa lưu trong trình duyệt sẽ bị mất. Chỉ dùng cách này khi bạn không thể tạo hồ sơ mới.",
  "",
  "1. Mở **Microsoft Edge**.",
  "2. Nhấn **Ctrl + Shift + N** hoặc bấm **Settings and more (⋯)** → **New InPrivate window**.",
  "3. Một cửa sổ giao diện tối sẽ mở ra với nhãn **\"InPrivate\"** ở góc trên bên trái.",
  "4. Truy cập URL của tenant đào tạo và đăng nhập bằng **thông tin đăng nhập đào tạo**.",
  "5. **Không đóng cửa sổ này** trong suốt phiên đào tạo.",
  "",
  "> 📖 **Tài liệu chính thức:** [Browse InPrivate in Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/browse-inprivate-in-microsoft-edge-e6f47704-340c-7d4f-b00d-d0cf35aa1fcc)",
  "",
  "---",
  "",
  "## Trình duyệt khác — Hướng dẫn thiết lập hồ sơ",
  "",
  "Nếu không dùng Microsoft Edge, hãy làm theo các hướng dẫn chính thức sau để tạo hồ sơ trình duyệt riêng:",
  "",
  "| Trình duyệt | Hướng dẫn |",
  "| --- | --- |",
  "| **Google Chrome** | [Create Chrome browser profiles](https://support.google.com/chrome/answer/2364824) |",
  "| **Mozilla Firefox** | [Profile Manager — Create, remove, or switch Firefox profiles](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) |",
  "",
  "Áp dụng cùng nguyên tắc: tạo hồ sơ mới, **không đăng nhập** bằng tài khoản công việc, sau đó chuyển đến URL của tenant đào tạo.",
].join('\n')

const mcpGuidanceEnglish = [
  "## Step by step guidance",
  "",
  "1. In the agent authoring experience, navigate to the **Tools** section.",
  "2. Click **+ Add tool**. ",
  "3. In the search box, enter **Microsoft Learn Docs MCP**. ",
  "4. Select **Microsoft Learn Docs MCP Server** from the search results.",
  "5. Click **Create a new connection** and **Add**.",
  "",
  "## Create the MCP Connection",
  "",
  "6. Click **Open connection manager**. ",
  "7. A new browser tab opens automatically.",
  "8. Click **Connect**.",
  "9. Review any permission prompts if presented.",
  "10. Click **Submit** to create the connection. ",
  "11. Click **Save** before closing the connection manager tab. ",
  "12. Return to Copilot Studio and click **Microsoft Learn Docs MCP Server**.",
  "13. Click **Maker** in Authentication Mode section.",
  "14. Click **Confirm** button to close the form.",
  "",
  "## Configure Agent Instructions",
  "",
  "15. Navigate to the **Overview** page of the agent. ",
  "16. In the **Instructions** section, append the following instruction to the end:",
  "",
  "   ```text",
  "   When users ask questions about Microsoft products, services, licensing,",
  "   architecture, APIs, or documentation, use the Microsoft Learn MCP Server",
  "   to search for answers and provide referenced responses.",
  "   ```",
].join('\n')

const mcpGuidanceVietnamese = [
  "## Hướng dẫn từng bước",
  "",
  "1. Trong trải nghiệm biên soạn Agent, chuyển đến phần **Tools**.",
  "2. Bấm **+ Add tool**.",
  "3. Trong ô tìm kiếm, nhập **Microsoft Learn Docs MCP**.",
  "4. Chọn **Microsoft Learn Docs MCP Server** trong kết quả tìm kiếm.",
  "5. Bấm **Create a new connection** rồi bấm **Add**.",
  "",
  "## Tạo kết nối MCP",
  "",
  "6. Bấm **Open connection manager**.",
  "7. Một tab trình duyệt mới sẽ tự động mở.",
  "8. Bấm **Connect**.",
  "9. Xem lại mọi lời nhắc cấp quyền nếu có.",
  "10. Bấm **Submit** để tạo kết nối.",
  "11. Bấm **Save** trước khi đóng tab connection manager.",
  "12. Quay lại Copilot Studio và bấm **Microsoft Learn Docs MCP Server**.",
  "13. Bấm **Maker** trong phần Authentication Mode.",
  "14. Bấm nút **Confirm** để đóng biểu mẫu.",
  "",
  "## Cấu hình hướng dẫn cho Agent",
  "",
  "15. Chuyển đến trang **Overview** của Agent.",
  "16. Trong phần **Instructions**, thêm hướng dẫn sau vào cuối:",
  "",
  "   ```text",
  "   When users ask questions about Microsoft products, services, licensing,",
  "   architecture, APIs, or documentation, use the Microsoft Learn MCP Server",
  "   to search for answers and provide referenced responses.",
  "   ```",
].join('\n')

const testAgentEnglish = [
  "## Test the agent",
  "",
  "1. Open the agent's **Preview** tab in modern agent maker experience portal.",
  "2. Ask a Microsoft-related question, for example:",
  "",
  "   ```text",
  "   Share with me some customers using copilot studio in energy and utility industry",
  "   ```",
  "",
  "   ```text",
  "   The Copilot Studio New Feature Updates and Roadmap in Oct Release 2026",
  "   ```",
  "",
  "3. Verify that the agent uses the **Microsoft Learn MCP Server** or *Microsoft Website* and returns responses grounded in those documentation.",
  "",
  "## Expected Result",
  "",
  "4. The agent is now connected to the **Microsoft Website** and **Microsoft Learn MCP Server**. ",
  "5. The agent can search documentation in real time and use Microsoft Website and Learn content to answer questions about Microsoft products and services.",
  "6. Click \"**Save**\" and then the \"**Publish**\" button on the top right corner of agent maker UI page.",
].join('\n')

const testAgentVietnamese = [
  "## Kiểm thử Agent",
  "",
  "1. Mở tab **Preview** của Agent trong cổng trải nghiệm Agent Maker hiện đại.",
  "2. Đặt một câu hỏi liên quan đến Microsoft, ví dụ:",
  "",
  "   ```text",
  "   Share with me some customers using copilot studio in energy and utility industry",
  "   ```",
  "",
  "   ```text",
  "   The Copilot Studio New Feature Updates and Roadmap in Oct Release 2026",
  "   ```",
  "",
  "3. Xác nhận Agent sử dụng **Microsoft Learn MCP Server** hoặc *Microsoft Website* và trả về câu trả lời có căn cứ từ các tài liệu đó.",
  "",
  "## Kết quả mong đợi",
  "",
  "4. Agent hiện đã kết nối với **Microsoft Website** và **Microsoft Learn MCP Server**.",
  "5. Agent có thể tìm kiếm tài liệu theo thời gian thực và dùng nội dung từ Microsoft Website cùng Microsoft Learn để trả lời câu hỏi về các sản phẩm và dịch vụ của Microsoft.",
  "6. Bấm \"**Save**\", sau đó bấm nút \"**Publish**\" ở góc trên bên phải trang Agent Maker UI.",
].join('\n')

export const lab01Vietnamese: Readonly<Record<string, string>> = {
  "Meet the new Agent Maker Experience": "Làm quen với trải nghiệm Agent Maker mới",
  "Create a multilingual Ask Me Anything agent grounded in Microsoft.com and Microsoft Learn MCP.": "Tạo Agent Ask Me Anything đa ngôn ngữ, dựa trên Microsoft.com và Microsoft Learn MCP.",
  "A grounded, multilingual agent ready for extension in the next labs.": "Một Agent đa ngôn ngữ, có căn cứ, sẵn sàng được mở rộng trong các bài thực hành tiếp theo.",
  "Navigate the modern Agent Create Experience, where the new Knowledge, Tools, Skills, and Memory surfaces.": "Khám phá Agent Create Experience hiện đại, nơi có các giao diện Knowledge, Tools, Skills và Memory mới.",
  "Ground answers with Microsoft.com and Microsoft Learn MCP.": "Cung cấp câu trả lời có căn cứ từ Microsoft.com và Microsoft Learn MCP.",
  "Apply language-aware agent instructions and test citations.": "Áp dụng hướng dẫn Agent nhận biết ngôn ngữ và kiểm tra trích dẫn.",
  "A Copilot Studio environment with maker access and generative AI enabled.": "Môi trường Copilot Studio có quyền truy cập maker và đã bật generative AI.",
  "Bring a personal laptop, or company laptop (make sure using another AAD demo account is not forbidden by your company policy.\u0020": "Mang theo máy tính xách tay cá nhân hoặc máy tính xách tay của công ty (hãy bảo đảm chính sách công ty không cấm sử dụng một tài khoản AAD demo khác).",
  "Open Microsoft Edge in new private window or Chrome browser in a new Incognito mode.   (Alternatively you can also create a new work/school browser user profile instead).": "Mở Microsoft Edge trong cửa sổ InPrivate mới hoặc Chrome ở chế độ Incognito mới. (Ngoài ra, bạn cũng có thể tạo hồ sơ người dùng trình duyệt work/school mới.)",
  "Browser Profile Setup": "Thiết lập hồ sơ trình duyệt",
  [liveBrowserProfileSetupEnglish]: liveBrowserProfileSetupVietnamese,
  "The same principle applies: create a new profile, **do not sign in** with your work account, then navigate to the training tenant URL.": "Áp dụng cùng nguyên tắc: tạo hồ sơ mới, **không đăng nhập** bằng tài khoản công việc, sau đó chuyển đến URL của tenant đào tạo.",
  "Create a Copilot Studio agent": "Tạo Agent trong Copilot Studio",
  "Start from the New Agent Create experience": "Bắt đầu từ trải nghiệm New Agent Create",
  "Open Copilot Studio and confirm that you are working in the **Training** environment assigned by your facilitator.   Select **Environment**, then search for **Training** environment.": "Mở Copilot Studio và xác nhận rằng bạn đang làm việc trong môi trường **Training** do người hướng dẫn chỉ định. Chọn **Environment**, sau đó tìm môi trường **Training**.",
  "Use the new agent experience. Do not switch to the classic authoring canvas in this lab.": "Sử dụng trải nghiệm Agent mới. Không chuyển sang classic authoring canvas trong bài thực hành này.",
  "Website in your browser": "Trang web trong trình duyệt",
  "Create a new Agent": "Tạo Agent mới",
  "The new creation experience begins with a natural-language description. Use it to establish the agent purpose before editing detailed settings.": "Trải nghiệm tạo mới bắt đầu bằng phần mô tả bằng ngôn ngữ tự nhiên. Hãy dùng phần này để xác định mục đích của Agent trước khi chỉnh sửa các cài đặt chi tiết.",
  "Name and review the agent": "Đặt tên và xem lại Agent",
  "Name the agent “Ask Me Anything” and choose the primary authoring language. Review the generated description and instructions before continuing.": "Đặt tên Agent là “Ask Me Anything” và chọn ngôn ngữ biên soạn chính. Xem lại phần mô tả và hướng dẫn được tạo trước khi tiếp tục.",
  "Create the agent and wait for the overview page to load. You should see the Knowledge, Tools, Skills, and Memory surfaces used throughout the remaining labs.": "Tạo Agent và chờ trang tổng quan tải xong. Bạn sẽ thấy các giao diện Knowledge, Tools, Skills và Memory được sử dụng trong những bài thực hành còn lại.",
  "Make sure you pick a unique name for your custom copilot.   Like the following naming pattern:  \"**Ask Me Anything Agent v2 – <Your Alias>**\", examine the following agent instruction, and copy and paste as the new agent's instruction.   Then click \"**Save**\" to save the agent.": "Hãy bảo đảm bạn chọn tên duy nhất cho custom copilot, theo mẫu: \"**Ask Me Anything Agent v2 – <Your Alias>**\". Xem hướng dẫn Agent bên dưới, sao chép rồi dán làm hướng dẫn cho Agent mới. Sau đó bấm \"**Save**\" để lưu Agent.",
  "Agent Name": "Tên Agent",
  "Agent Instruction": "Hướng dẫn cho Agent",
  "Add trusted public knowledge": "Thêm nguồn kiến thức công khai đáng tin cậy",
  "On Knowledge, add **https://www.microsoft.com** as a public website. Scope the source description to official product and company information.": "Trong Knowledge, thêm **https://www.microsoft.com** làm trang web công khai. Giới hạn phần mô tả nguồn ở thông tin chính thức về sản phẩm và công ty.",
  "Knowledge / Public Websites": "Knowledge / Trang web công khai",
  "Connect Microsoft Learn MCP": "Kết nối Microsoft Learn MCP",
  "Open Tools, add an MCP server, and register the Microsoft Learn MCP endpoint supplied by your facilitator. Review the discovered documentation tools before enabling them.": "Mở Tools, thêm một MCP server và đăng ký endpoint Microsoft Learn MCP do người hướng dẫn cung cấp. Xem lại các công cụ tài liệu được phát hiện trước khi bật chúng.",
  [mcpGuidanceEnglish]: mcpGuidanceVietnamese,
  "Tenant policy can restrict remote MCP servers. Use the facilitator-approved endpoint and authentication method.": "Chính sách tenant có thể hạn chế các MCP server từ xa. Hãy dùng endpoint và phương thức xác thực đã được người hướng dẫn phê duyệt.",
  "New instruction to append at the end of the Agent Instruction": "Hướng dẫn mới cần thêm vào cuối Agent Instruction",
  "Add prompt and test": "Thêm prompt và kiểm thử",
  "Paste the instructions below, save, and test the same product question in **English, Chinese, Japanese, and Korean**. Confirm that answers stay grounded and contain useful source links.": "Dán các hướng dẫn bên dưới, lưu lại và kiểm thử cùng một câu hỏi về sản phẩm bằng **tiếng Anh, tiếng Trung, tiếng Nhật và tiếng Hàn**. Xác nhận rằng câu trả lời vẫn có căn cứ và chứa các liên kết nguồn hữu ích.",
  [testAgentEnglish]: testAgentVietnamese,
  "Test Prompt 1": "Prompt kiểm thử 1",
  "Test Prompt 2": "Prompt kiểm thử 2",
  "Meet the new agent experience": "Làm quen với trải nghiệm Agent mới",
  "Navigate the modern Create, Knowledge, Tools, Skills, and Memory surfaces.": "Khám phá các giao diện Create, Knowledge, Tools, Skills và Memory hiện đại.",
  [bundledBrowserProfileSetupEnglish]: bundledBrowserProfileSetupVietnamese,
  "Create the agent": "Tạo Agent",
  "Start from the Create experience": "Bắt đầu từ trải nghiệm Create",
  "Open Copilot Studio and confirm that you are working in the environment assigned by your facilitator. Select Create, then New agent.": "Mở Copilot Studio và xác nhận rằng bạn đang làm việc trong môi trường do người hướng dẫn chỉ định. Chọn Create, sau đó chọn New agent.",
  "On Knowledge, add https://www.microsoft.com as a public website. Scope the source description to official product and company information.": "Trong Knowledge, thêm https://www.microsoft.com làm trang web công khai. Giới hạn phần mô tả nguồn ở thông tin chính thức về sản phẩm và công ty.",
  "Add instructions and test": "Thêm hướng dẫn và kiểm thử",
  "Paste the instructions below, save, and test the same product question in English, Chinese, Japanese, and Korean. Confirm that answers stay grounded and contain useful source links.": "Dán các hướng dẫn bên dưới, lưu lại và kiểm thử cùng một câu hỏi về sản phẩm bằng tiếng Anh, tiếng Trung, tiếng Nhật và tiếng Hàn. Xác nhận rằng câu trả lời vẫn có căn cứ và chứa các liên kết nguồn hữu ích.",
}