const dataverseSetupEnglish = [
  "## Add the Microsoft Dataverse MCP Tool",
  "",
  "1. Open your agent in the **new Copilot Studio Agent Experience**.",
  "2. Scroll to the **Tools** section.",
  "3. Click **+ Add tool**.",
  "4. Select **Model Context Protocol (MCP)**.",
  "5. Search for **Dataverse**.",
  "6. Select **Microsoft Dataverse MCP Server**.",
  "7. If prompted, create or select a **Dataverse connection**.",
  "8. Click **Add to agent**.",
  "",
  "## Configure Available MCP Tools (Optional)",
  "",
  "9. Next to **Microsoft Dataverse MCP Server**, click **⋯ → Edit**.",
  "10. Review the available tools exposed by the MCP Server.",
  "11. Disable any tools that should not be available to the agent.",
].join('\n')

const dataverseSetupVietnamese = [
  "## Thêm công cụ Microsoft Dataverse MCP",
  "",
  "1. Mở Agent của bạn trong **new Copilot Studio Agent Experience**.",
  "2. Cuộn đến phần **Tools**.",
  "3. Bấm **+ Add tool**.",
  "4. Chọn **Model Context Protocol (MCP)**.",
  "5. Tìm kiếm **Dataverse**.",
  "6. Chọn **Microsoft Dataverse MCP Server**.",
  "7. Nếu được nhắc, hãy tạo hoặc chọn một **Dataverse connection**.",
  "8. Bấm **Add to agent**.",
  "",
  "## Cấu hình các công cụ MCP khả dụng (Không bắt buộc)",
  "",
  "9. Bên cạnh **Microsoft Dataverse MCP Server**, bấm **⋯ → Edit**.",
  "10. Xem lại các công cụ khả dụng do MCP Server cung cấp.",
  "11. Tắt mọi công cụ mà Agent không được phép sử dụng.",
].join('\n')

const dataverseTestEnglish = [
  "## Test the Dataverse MCP Tool",
  "",
  "1. Open the **Preview** tab.",
  "2. Ask the agent a Dataverse-related question, such as:",
  "",
  "   ```text",
  "   Show me the Top 20 my active accounts.",
  "   ```",
  "",
  "   ```text",
  "   create new account with name \"New Account 123\", www.nameaccount123.com,\u0020",
  "   and it's located in Shanghai, China.",
  "   ```",
  "",
  "3. Verify that the agent invokes the **Microsoft Dataverse MCP Server** and returns results from Dataverse.",
  "",
  "## Expected Result",
  "",
  "4. The agent is now connected to the **Microsoft Dataverse MCP Server**.",
  "5. The agent can discover Dataverse tables, understand schemas, search records, query data, and perform Dataverse operations through MCP tools based on your permissions and environment settings.",
].join('\n')

const dataverseTestVietnamese = [
  "## Kiểm thử công cụ Dataverse MCP",
  "",
  "1. Mở tab **Preview**.",
  "2. Đặt cho Agent một câu hỏi liên quan đến Dataverse, chẳng hạn như:",
  "",
  "   ```text",
  "   Show me the Top 20 my active accounts.",
  "   ```",
  "",
  "   ```text",
  "   create new account with name \"New Account 123\", www.nameaccount123.com,\u0020",
  "   and it's located in Shanghai, China.",
  "   ```",
  "",
  "3. Xác nhận rằng Agent gọi **Microsoft Dataverse MCP Server** và trả về kết quả từ Dataverse.",
  "",
  "## Kết quả mong đợi",
  "",
  "4. Agent hiện đã được kết nối với **Microsoft Dataverse MCP Server**.",
  "5. Agent có thể khám phá các bảng Dataverse, hiểu schema, tìm kiếm bản ghi, truy vấn dữ liệu và thực hiện các thao tác Dataverse thông qua công cụ MCP dựa trên quyền của bạn và cài đặt môi trường.",
].join('\n')

const skillSetupEnglish = [
  "Here are the brief step-by-step instructions to create a new **skill** in the modern (new experience) agent maker in Copilot Studio:",
  "",
  "1. Open your agent in **Copilot Studio** (or create one first if you don't have one yet).",
  "2. Select the **Build** tab.",
  "3. In the components panel, select **Skills**.",
  "4. In **Add skill**, click **Create from blank**. (Alternatively, choose **Upload a skill** to import a `.md` file or skill `.zip` package.)",
  "5. Enter a **Name** — use only lowercase letters, numbers, and hyphens, and don't start or end with a hyphen (e.g., `account-360-generator` or `customer-support-escalation`).",
  "6. Enter a **Description** of what the skill does and when it should activate. (This is what the orchestrator uses to decide when to invoke the skill — be specific.)",
  "7. Write the **Instructions** in **Markdown** — include the steps the agent should follow, response format, constraints, edge cases, and any tools it should use.",
  "8. Click **Create**. The skill now appears in the components panel for your agent.",
].join('\n')

const skillSetupVietnamese = [
  "Dưới đây là hướng dẫn ngắn gọn từng bước để tạo một **skill** mới trong trải nghiệm Agent Maker hiện đại (trải nghiệm mới) của Copilot Studio:",
  "",
  "1. Mở Agent của bạn trong **Copilot Studio** (hoặc tạo một Agent trước nếu bạn chưa có).",
  "2. Chọn tab **Build**.",
  "3. Trong bảng components, chọn **Skills**.",
  "4. Trong **Add skill**, bấm **Create from blank**. (Ngoài ra, chọn **Upload a skill** để nhập tệp `.md` hoặc gói skill `.zip`.)",
  "5. Nhập **Name** — chỉ sử dụng chữ cái viết thường, chữ số và dấu gạch nối; không bắt đầu hoặc kết thúc bằng dấu gạch nối (ví dụ: `account-360-generator` hoặc `customer-support-escalation`).",
  "6. Nhập **Description** mô tả chức năng của skill và thời điểm skill nên kích hoạt. (Orchestrator sử dụng nội dung này để quyết định khi nào gọi skill, vì vậy hãy mô tả cụ thể.)",
  "7. Viết **Instructions** bằng **Markdown** — bao gồm các bước Agent cần làm theo, định dạng phản hồi, ràng buộc, trường hợp biên và mọi công cụ cần sử dụng.",
  "8. Bấm **Create**. Skill giờ sẽ xuất hiện trong bảng components của Agent.",
].join('\n')

const memoryDisabledEnglish = [
  "Open your agent in **Copilot Studio** and select the **Build** tab and locate the **Memory** component in the components panel — this is where the **Memory toggle** lives.",
  "",
  "---",
  "",
  "## Part A — Memory = Disabled (no recall across sessions)",
  "",
  "1. On the **Build** tab, set the **Memory toggle** to **Off**.",
  "2. Open the **Preview** tab (the test chat on the right).",
  "3. In the chat, type: **`My big bet account for this FY is Microsoft.`** and send. → The agent acknowledges it for the current conversation.",
  "4. Next, type: **`Account plan for my big bet account.`** → **Expected result:** The agent produces a brief **for Microsoft** — it still \"knows\" because Microsoft is sitting in the *current conversation's* short-term context.",
  "5. Now **start a new test**: click the **Refresh / restart conversation** icon at the top of the **Preview** pane (this begins a fresh session).",
  "6. In the new session, type again: **`Account plan for my big bet account.`** → **Expected result:** The agent **does not know** which account you mean. It asks you to name the account (or gives a generic answer), because with Memory off, nothing was saved once the previous conversation ended.",
].join('\n')

const memoryDisabledVietnamese = [
  "Mở Agent của bạn trong **Copilot Studio**, chọn tab **Build**, rồi tìm component **Memory** trong bảng components — đây là nơi có **Memory toggle**.",
  "",
  "---",
  "",
  "## Phần A — Memory = Disabled (không nhớ giữa các phiên)",
  "",
  "1. Trên tab **Build**, đặt **Memory toggle** thành **Off**.",
  "2. Mở tab **Preview** (khung chat kiểm thử ở bên phải).",
  "3. Trong khung chat, nhập: **`My big bet account for this FY is Microsoft.`** rồi gửi. → Agent ghi nhận thông tin này trong cuộc hội thoại hiện tại.",
  "4. Tiếp theo, nhập: **`Account plan for my big bet account.`** → **Kết quả mong đợi:** Agent tạo một bản tóm tắt **cho Microsoft** — Agent vẫn \"biết\" vì Microsoft đang nằm trong ngữ cảnh ngắn hạn của *cuộc hội thoại hiện tại*.",
  "5. Bây giờ hãy **bắt đầu một lượt kiểm thử mới**: bấm biểu tượng **Refresh / restart conversation** ở đầu khung **Preview** (thao tác này bắt đầu một phiên mới).",
  "6. Trong phiên mới, nhập lại: **`Account plan for my big bet account.`** → **Kết quả mong đợi:** Agent **không biết** bạn đang đề cập đến tài khoản nào. Agent yêu cầu bạn nêu tên tài khoản (hoặc đưa ra câu trả lời chung) vì khi Memory tắt, không có gì được lưu sau khi cuộc hội thoại trước kết thúc.",
].join('\n')

const memoryEnabledEnglish = [
  "## Part B — Memory = Enabled (recall across sessions)",
  "",
  "1. Go back to the **Build** tab and set the **Memory toggle** to **On**.",
  "2. Open the **Preview** tab and type: **`My big bet account is Microsoft.`** and send. → With Memory on, the agent **captures and stores** this preference in your per-user memory store. *(The first response from a memory-enabled agent also includes a link to the memory portal, where you can confirm the stored memory.)*",
  "3. **Restart the testing**: click the **Refresh / restart conversation** icon at the top of the **Preview** pane to begin a brand-new session.",
  "4. In the fresh session, type: **`Account brief for my big bet account.`** → **Expected result:** The agent **recalls \"Microsoft\" from memory** — even though you never mentioned it in this new session — and returns the Microsoft account brief directly.",
  "5. Don't forget to **Save** the agent with the enabled memory setup.",
].join('\n')

const memoryEnabledVietnamese = [
  "## Phần B — Memory = Enabled (ghi nhớ giữa các phiên)",
  "",
  "1. Quay lại tab **Build** và đặt **Memory toggle** thành **On**.",
  "2. Mở tab **Preview**, nhập: **`My big bet account is Microsoft.`** rồi gửi. → Khi Memory bật, Agent **thu thập và lưu trữ** tùy chọn này trong kho Memory riêng của bạn. *(Phản hồi đầu tiên từ Agent đã bật Memory cũng bao gồm liên kết đến memory portal, nơi bạn có thể xác nhận Memory đã lưu.)*",
  "3. **Khởi động lại lượt kiểm thử**: bấm biểu tượng **Refresh / restart conversation** ở đầu khung **Preview** để bắt đầu một phiên hoàn toàn mới.",
  "4. Trong phiên mới, nhập: **`Account brief for my big bet account.`** → **Kết quả mong đợi:** Agent **nhớ lại \"Microsoft\" từ Memory** — dù bạn chưa hề nhắc đến tên này trong phiên mới — và trả về ngay bản tóm tắt tài khoản Microsoft.",
  "5. Đừng quên bấm **Save** để lưu Agent với thiết lập Memory đã bật.",
].join('\n')

const memorySummaryEnglish = [
  "## Side-by-side result",
  "",
  "| Test | Memory | New session? | \"Account brief for my big bet account\" → |",
  "|------|--------|--------------|-------------------------------------------|",
  "| A-1 | Off | No (same chat) | Returns Microsoft brief (from live context) |",
  "| A-2 | Off | Yes (new chat) | Doesn't remember — asks which account |",
  "| B | On | Yes (new chat) | Remembers Microsoft — returns brief |",
  "",
  "---",
  "",
  "## Notes & gotchas",
  "",
  "- The **Memory toggle** is on the **Build** tab, in the components panel — it's an **agent-level** setting the maker controls.",
  "- Memories are stored **per user, per agent** and are never shared with other users.",
  "- **Turning Memory off does *not* delete** existing memories — it only stops the agent from using them. To truly reset, delete them in the memory portal (or ask the agent in chat to \"forget my big bet account\").",
  "- If you don't interact with a memory-enabled agent for **28 days**, your memories for it are automatically cleared.",
  "- Memory is currently a **preview** feature in the new experience.",
  "- For a sharper brief, make sure your agent has the relevant **Knowledge / Microsoft IQ** connected so \"account brief\" draws on real account data rather than generic reasoning.",
].join('\n')

const memorySummaryVietnamese = [
  "## Kết quả đối chiếu",
  "",
  "| Kiểm thử | Memory | Phiên mới? | \"Account brief for my big bet account\" → |",
  "|------|--------|--------------|-------------------------------------------|",
  "| A-1 | Off | Không (cùng cuộc chat) | Trả về bản tóm tắt Microsoft (từ ngữ cảnh hiện tại) |",
  "| A-2 | Off | Có (cuộc chat mới) | Không nhớ — hỏi bạn muốn nói đến tài khoản nào |",
  "| B | On | Có (cuộc chat mới) | Nhớ Microsoft — trả về bản tóm tắt |",
  "",
  "---",
  "",
  "## Lưu ý và điểm cần chú ý",
  "",
  "- **Memory toggle** nằm trong bảng components trên tab **Build** — đây là cài đặt ở **cấp Agent** do maker kiểm soát.",
  "- Memory được lưu **riêng cho từng người dùng, từng Agent** và không bao giờ được chia sẻ với người dùng khác.",
  "- **Tắt Memory *không* xóa** Memory hiện có — thao tác này chỉ ngăn Agent sử dụng chúng. Để đặt lại hoàn toàn, hãy xóa chúng trong memory portal (hoặc yêu cầu Agent trong chat: \"forget my big bet account\").",
  "- Nếu bạn không tương tác với Agent đã bật Memory trong **28 ngày**, Memory của bạn dành cho Agent đó sẽ tự động bị xóa.",
  "- Memory hiện là một tính năng **preview** trong trải nghiệm mới.",
  "- Để có bản tóm tắt chính xác hơn, hãy bảo đảm Agent đã kết nối **Knowledge / Microsoft IQ** liên quan để \"account brief\" dựa trên dữ liệu tài khoản thực thay vì suy luận chung chung.",
].join('\n')

const coworkWorkflowEnglish = [
  "1. In **Copilot Studio**, select **Workflows** in the left navigation.",
  "2. Select **JumpStart - Get Customer Updates Workflow v2**, then open the **Build** tab to load the **designer canvas**.",
  "3. Use the bottom-left toolbar — **Fit view** and **Tidy up** — to lay out the full flow so you can read it end to end. (Click any node to open its **configuration panel** on the right.)",
  "",
  "Walk through each node:",
  "",
  "**① Trigger — \"When an agent calls the flow\"**",
  "- Confirm the input parameter the agent will pass in (e.g., **`Customer name`**, Text). This is what the calling agent fills with the customer, such as *Microsoft*.",
  "",
  "**② Microsoft 365 Copilot node — the Cowork call (examine closely)**",
  "- Open the node and verify the key settings:",
  "  - **Message** — check that the prompt asks for external customer dynamics/updates and that it references the **`{Customer name}`** token (inserted via the dynamic content picker), so the call reasons over the runtime value.",
  "  - **Advanced parameters → Agent** — confirm it's set to **Cowork**. This is what routes the step to M365 Cowork rather than general Microsoft 365 Copilot; Cowork's own instructions, knowledge, and tools apply.",
  "  - **Prefer Async** — should be **Off** so the workflow **waits** for Cowork's response before continuing.",
  "  - **Time Zone** — set to match the running user so relative dates resolve correctly.",
  "  - **Sign-in / connection** — confirm the node is connected to a valid Microsoft 365 account (it runs on that user's behalf).",
  "",
  "**③ \"Respond to the agent\" node**",
  "- Confirm the response output is mapped to the **M365 Copilot** node's **response** — this is what returns Cowork's customer-dynamics brief to the calling agent.",
  "- Check the canvas for any **red error** markers; a workflow with errors can't be used reliably.",
  "",
].join('\n')

const coworkWorkflowVietnamese = [
  "1. Trong **Copilot Studio**, chọn **Workflows** ở thanh điều hướng bên trái.",
  "2. Chọn **JumpStart - Get Customer Updates Workflow v2**, sau đó mở tab **Build** để tải **designer canvas**.",
  "3. Dùng thanh công cụ ở góc dưới bên trái — **Fit view** và **Tidy up** — để bố trí toàn bộ flow sao cho bạn có thể đọc từ đầu đến cuối. (Bấm vào bất kỳ node nào để mở **configuration panel** của node đó ở bên phải.)",
  "",
  "Xem xét lần lượt từng node:",
  "",
  "**① Trigger — \"When an agent calls the flow\"**",
  "- Xác nhận tham số đầu vào mà Agent sẽ truyền vào (ví dụ: **`Customer name`**, Text). Agent gọi flow sẽ điền tên khách hàng vào đây, chẳng hạn như *Microsoft*.",
  "",
  "**② Node Microsoft 365 Copilot — lệnh gọi Cowork (xem xét kỹ)**",
  "- Mở node và xác minh các cài đặt chính:",
  "  - **Message** — kiểm tra rằng prompt yêu cầu thông tin động thái/cập nhật bên ngoài về khách hàng và tham chiếu token **`{Customer name}`** (được chèn bằng dynamic content picker), để lệnh gọi suy luận dựa trên giá trị tại runtime.",
  "  - **Advanced parameters → Agent** — xác nhận giá trị được đặt thành **Cowork**. Cài đặt này định tuyến bước đến M365 Cowork thay vì Microsoft 365 Copilot chung; các instructions, knowledge và tools riêng của Cowork sẽ được áp dụng.",
  "  - **Prefer Async** — phải là **Off** để workflow **chờ** phản hồi của Cowork trước khi tiếp tục.",
  "  - **Time Zone** — đặt khớp với người dùng đang chạy để các ngày tương đối được diễn giải chính xác.",
  "  - **Sign-in / connection** — xác nhận node được kết nối với một tài khoản Microsoft 365 hợp lệ (node chạy thay mặt người dùng đó).",
  "",
  "**③ Node \"Respond to the agent\"**",
  "- Xác nhận đầu ra phản hồi được ánh xạ đến **response** của node **M365 Copilot** — đây là nội dung trả bản tóm tắt động thái khách hàng của Cowork về cho Agent gọi flow.",
  "- Kiểm tra canvas để tìm mọi dấu **red error**; workflow có lỗi sẽ không thể được sử dụng một cách tin cậy.",
  "",
].join('\n')

const addCoworkWorkflowEnglish = [
  "1. Open your **agent** and select the **Build** tab.",
  "2. In the components panel, select **Tools**.",
  "3. In the **Add a tool** dialog, open the **Workflows** tab (or search) and locate **JumpStart - Get Customer Updates Workflow v2**.",
  "4. Select it to view its details, then select **Add**.",
  "5. Review the tool's **description** so it clearly states *when* to use it (e.g., \"gets external customer dynamics/updates for Customer 360 enrichment\") \uFFFD\uFFFD\uFFFD\uFFFD the orchestrator relies on this to invoke the tool correctly.",
].join('\n')

const addCoworkWorkflowVietnamese = [
  "1. Mở **agent** của bạn và chọn tab **Build**.",
  "2. Trong bảng components, chọn **Tools**.",
  "3. Trong hộp thoại **Add a tool**, mở tab **Workflows** (hoặc tìm kiếm) và tìm **JumpStart - Get Customer Updates Workflow v2**.",
  "4. Chọn workflow để xem chi tiết, sau đó chọn **Add**.",
  "5. Xem lại **description** của công cụ để nội dung nêu rõ *khi nào* nên sử dụng công cụ (ví dụ: \"gets external customer dynamics/updates for Customer 360 enrichment\"); orchestrator dựa vào nội dung này để gọi công cụ chính xác.",
].join('\n')

const coworkTestEnglish = [
  "1. Open the agent's **Preview** tab.",
  "2. Enter a prompt that should trigger the tool, for example:",
  "    \"**`Get the latest company news and updates for Microsoft (in last 12 months).`**\"",
  "3. Watch the agent **invoke JumpStart - Get Customer Updates Workflow v2**, which calls **Cowork** via the M365 Copilot node and returns the enrichment brief in the chat.",
  "4. To inspect node-level behavior, you can also open the workflow in the designer and use **Run flow test** (Play button) or **Test this node** on the M365 Copilot step — supply a sample customer name and review the raw output. *(Designer and test-chat runs don't consume flow capacity.)*",
  "5. Click **Save**, and then **Publish** to publish the agent.",
].join('\n')

const coworkTestVietnamese = [
  "1. Mở tab **Preview** của Agent.",
  "2. Nhập một prompt có khả năng kích hoạt công cụ, ví dụ:",
  "    \"**`Get the latest company news and updates for Microsoft (in last 12 months).`**\"",
  "3. Theo dõi Agent **invoke JumpStart - Get Customer Updates Workflow v2**; workflow này gọi **Cowork** qua node M365 Copilot và trả bản tóm tắt bổ sung vào khung chat.",
  "4. Để kiểm tra hành vi ở cấp node, bạn cũng có thể mở workflow trong designer và dùng **Run flow test** (nút Play) hoặc **Test this node** ở bước M365 Copilot — cung cấp một tên khách hàng mẫu và xem lại đầu ra thô. *(Các lượt chạy trong designer và test-chat không tiêu tốn dung lượng flow.)*",
  "5. Bấm **Save**, sau đó bấm **Publish** để phát hành Agent.",
].join('\n')

const coworkQuickChecksEnglish = [
  "## Quick checks if the result looks off",
  "",
  "- **Empty/generic brief** → re-open the M365 Copilot node and confirm **Agent = Cowork** and that the **`{inputCustomerResearchRequest}`** input is actually inserted in the Message.",
  "- **Agent didn't call the tool** → tighten the tool **name/description** so it clearly matches \"customer updates / dynamics / enrichment.\"",
].join('\n')

const coworkQuickChecksVietnamese = [
  "## Kiểm tra nhanh nếu kết quả có vẻ không đúng",
  "",
  "- **Bản tóm tắt trống/chung chung** → mở lại node M365 Copilot và xác nhận **Agent = Cowork**, đồng thời bảo đảm đầu vào **`{inputCustomerResearchRequest}`** thực sự được chèn vào Message.",
  "- **Agent không gọi công cụ** → điều chỉnh **name/description** của công cụ để khớp rõ ràng với \"customer updates / dynamics / enrichment.\"",
].join('\n')

const m365WorkflowEnglish = [
  "1. In **Copilot Studio**, select **Workflows** in the left navigation.",
  "2. Select **JumpStart - Get Customer Updates Workflow v2**, then open the **Build** tab to load the **designer canvas**.",
  "3. Use the bottom-left toolbar — **Fit view** and **Tidy up** — to lay out the full flow so you can read it end to end. (Click any node to open its **configuration panel** on the right.)",
  "",
  "Walk through each node:",
  "",
  "**① Trigger — \"When an agent calls the flow\"**",
  "- Confirm the input parameter the agent will pass in (e.g., **`Customer name`**, Text). This is what the calling agent fills with the customer, such as *Microsoft*.",
  "",
  "**② Microsoft 365 Copilot node — the M365 Copilot call (examine closely)**",
  "- Open the node and verify the key settings:",
  "  - **Message** — check that the prompt asks for external customer dynamics/updates and that it references the **`{Customer name}`** token (inserted via the dynamic content picker), so the call reasons over the runtime value.",
  "  - **Advanced parameters → Agent** — confirm it's set to **Empty**. This is what routes the step to M365 Copilot rather than general Microsoft 365 Agent.",
  "  - **Prefer Async** — should be **Off** so the workflow **waits** for Researcher's response before continuing.",
  "  - **Time Zone** — set to match the running user so relative dates resolve correctly.",
  "  - **Sign-in / connection** — confirm the node is connected to a valid Microsoft 365 account (it runs on that user's behalf).",
  "",
  "**③ \"Respond to the agent\" node**",
  "- Confirm the response output is mapped to the **M365 Copilot** node's **response** — this is what returns M365 Copilot's customer-dynamics brief to the calling agent.",
  "- Check the canvas for any **red error** markers; a workflow with errors can't be used reliably.",
  "",
].join('\n')

const m365WorkflowVietnamese = [
  "1. Trong **Copilot Studio**, chọn **Workflows** ở thanh điều hướng bên trái.",
  "2. Chọn **JumpStart - Get Customer Updates Workflow v2**, sau đó mở tab **Build** để tải **designer canvas**.",
  "3. Dùng thanh công cụ ở góc dưới bên trái — **Fit view** và **Tidy up** — để bố trí toàn bộ flow sao cho bạn có thể đọc từ đầu đến cuối. (Bấm vào bất kỳ node nào để mở **configuration panel** của node đó ở bên phải.)",
  "",
  "Xem xét lần lượt từng node:",
  "",
  "**① Trigger — \"When an agent calls the flow\"**",
  "- Xác nhận tham số đầu vào mà Agent sẽ truyền vào (ví dụ: **`Customer name`**, Text). Agent gọi flow sẽ điền tên khách hàng vào đây, chẳng hạn như *Microsoft*.",
  "",
  "**② Node Microsoft 365 Copilot — lệnh gọi M365 Copilot (xem xét kỹ)**",
  "- Mở node và xác minh các cài đặt chính:",
  "  - **Message** — kiểm tra rằng prompt yêu cầu thông tin động thái/cập nhật bên ngoài về khách hàng và tham chiếu token **`{Customer name}`** (được chèn bằng dynamic content picker), để lệnh gọi suy luận dựa trên giá trị tại runtime.",
  "  - **Advanced parameters → Agent** — xác nhận giá trị được đặt thành **Empty**. Cài đặt này định tuyến bước đến M365 Copilot thay vì Microsoft 365 Agent chung.",
  "  - **Prefer Async** — phải là **Off** để workflow **chờ** phản hồi của Researcher trước khi tiếp tục.",
  "  - **Time Zone** — đặt khớp với người dùng đang chạy để các ngày tương đối được diễn giải chính xác.",
  "  - **Sign-in / connection** — xác nhận node được kết nối với một tài khoản Microsoft 365 hợp lệ (node chạy thay mặt người dùng đó).",
  "",
  "**③ Node \"Respond to the agent\"**",
  "- Xác nhận đầu ra phản hồi được ánh xạ đến **response** của node **M365 Copilot** — đây là nội dung trả bản tóm tắt động thái khách hàng của M365 Copilot về cho Agent gọi flow.",
  "- Kiểm tra canvas để tìm mọi dấu **red error**; workflow có lỗi sẽ không thể được sử dụng một cách tin cậy.",
  "",
].join('\n')

const addM365WorkflowEnglish = [
  "1. Open your **agent** and select the **Build** tab.",
  "2. In the components panel, select **Tools**.",
  "3. In the **Add a tool** dialog, open the **Workflows** tab (or search) and locate **JumpStart - Get Customer Updates Workflow v2**.",
  "4. Select it to view its details, then select **Add**.",
  "5. Review the tool's **description** so it clearly states *when* to use it (e.g., \"gets external customer dynamics/updates for Customer 360 enrichment\")  the orchestrator relies on this to invoke the tool correctly.",
].join('\n')

const addM365WorkflowVietnamese = [
  "1. Mở **agent** của bạn và chọn tab **Build**.",
  "2. Trong bảng components, chọn **Tools**.",
  "3. Trong hộp thoại **Add a tool**, mở tab **Workflows** (hoặc tìm kiếm) và tìm **JumpStart - Get Customer Updates Workflow v2**.",
  "4. Chọn workflow để xem chi tiết, sau đó chọn **Add**.",
  "5. Xem lại **description** của công cụ để nội dung nêu rõ *khi nào* nên sử dụng công cụ (ví dụ: \"gets external customer dynamics/updates for Customer 360 enrichment\"); orchestrator dựa vào nội dung này để gọi công cụ chính xác.",
].join('\n')

const m365TestEnglish = [
  "1. Open the agent's **Preview** tab.",
  "2. Enter a prompt that should trigger the tool, for example:",
  "    \"**`Get the latest company news and updates for Microsoft (in last 3 months).`**\"",
  "3. Watch the agent **invoke JumpStart - Get Customer Updates Workflow v2**, which calls **M365 Copilot** via the M365 Copilot node and returns the enrichment brief in the chat.",
  "4. To inspect node-level behavior, you can also open the workflow in the designer and use **Run flow test** (Play button) or **Test this node** on the M365 Copilot step — supply a sample customer name and review the raw output. *(Designer and test-chat runs don't consume flow capacity.)*",
  "5. Click **Save**, and then **Publish** to publish the agent.",
].join('\n')

const m365TestVietnamese = [
  "1. Mở tab **Preview** của Agent.",
  "2. Nhập một prompt có khả năng kích hoạt công cụ, ví dụ:",
  "    \"**`Get the latest company news and updates for Microsoft (in last 3 months).`**\"",
  "3. Theo dõi Agent **invoke JumpStart - Get Customer Updates Workflow v2**; workflow này gọi **M365 Copilot** qua node M365 Copilot và trả bản tóm tắt bổ sung vào khung chat.",
  "4. Để kiểm tra hành vi ở cấp node, bạn cũng có thể mở workflow trong designer và dùng **Run flow test** (nút Play) hoặc **Test this node** ở bước M365 Copilot — cung cấp một tên khách hàng mẫu và xem lại đầu ra thô. *(Các lượt chạy trong designer và test-chat không tiêu tốn dung lượng flow.)*",
  "5. Bấm **Save**, sau đó bấm **Publish** để phát hành Agent.",
].join('\n')

const m365QuickChecksEnglish = [
  "## Quick checks if the result looks off",
  "",
  "- **Empty/generic brief** → re-open the M365 Copilot node and confirm **Agent is Empty** and that the **`{inputCustomerResearchRequest}`** input is actually inserted in the Message.",
  "- **Agent didn't call the tool** → tighten the tool **name/description** so it clearly matches \"customer updates / dynamics / enrichment.\"",
].join('\n')

const m365QuickChecksVietnamese = [
  "## Kiểm tra nhanh nếu kết quả có vẻ không đúng",
  "",
  "- **Bản tóm tắt trống/chung chung** → mở lại node M365 Copilot và xác nhận **Agent is Empty**, đồng thời bảo đảm đầu vào **`{inputCustomerResearchRequest}`** thực sự được chèn vào Message.",
  "- **Agent không gọi công cụ** → điều chỉnh **name/description** của công cụ để khớp rõ ràng với \"customer updates / dynamics / enrichment.\"",
].join('\n')

export const lab02Vietnamese: Readonly<Record<string, string>> = {
  "Bring in business context": "Tích hợp bối cảnh kinh doanh",
  "Use Dataverse MCP, Skills, Memory, and a Researcher/CoWork workflow to build an account-aware assistant.": "Sử dụng Dataverse MCP, Skills, Memory và workflow Researcher/CoWork để xây dựng một trợ lý am hiểu tài khoản.",
  "An agent that retrieves your active accounts, remembers Big Bets, and creates a sourced customer 360.": "Một Agent có thể truy xuất các tài khoản đang hoạt động của bạn, ghi nhớ Big Bets và tạo Customer 360 có nguồn dẫn.",
  "Connect Dataverse MCP with user-scoped access.": "Kết nối Dataverse MCP với quyền truy cập theo phạm vi người dùng.",
  "Create a reusable Skill for account planning.": "Tạo một Skill có thể tái sử dụng cho việc lập kế hoạch tài khoản.",
  "Combine durable Memory with fresh external Researcher/Cowork's research.": "Kết hợp Memory bền vững với nghiên cứu bên ngoài mới nhất từ Researcher/Cowork.",
  "Complete Lab 1 and have read access to the facilitator Dataverse sample data.": "Hoàn thành bài thực hành 1 và có quyền đọc dữ liệu mẫu Dataverse của người hướng dẫn.",
  "Add Dataverse MCP": "Thêm Dataverse MCP",
  "In Tools, connect the facilitator-provided Dataverse MCP server with user authentication.": "Trong Tools, kết nối Dataverse MCP server do người hướng dẫn cung cấp bằng xác thực người dùng.",
  [dataverseSetupEnglish]: dataverseSetupVietnamese,
  "**Prerequisite:** The Dataverse MCP Server must be enabled for the Power Platform environment.": "**Điều kiện tiên quyết:** Dataverse MCP Server phải được bật cho môi trường Power Platform.",
  "Test the Dataverse MCP Server by asking account related questions.": "Kiểm thử Dataverse MCP Server bằng cách đặt các câu hỏi liên quan đến tài khoản.",
  [dataverseTestEnglish]: dataverseTestVietnamese,
  "Click \"**Allow**\" button when you use the **Dataverse MCP Tool** the first time to answer your question in the **Preview** Tab to test the agent.": "Bấm nút \"**Allow**\" khi bạn sử dụng **Dataverse MCP Tool** lần đầu để trả lời câu hỏi trong tab **Preview** và kiểm thử Agent.",
  "Test Prompt 1": "Prompt kiểm thử 1",
  "Test Prompt 2": "Prompt kiểm thử 2",
  "Get your **Account 360** using Skill": "Tạo **Account 360** của bạn bằng Skill",
  "Create a new Skill": "Tạo Skill mới",
  "Open Skills, create a skill named Account Planning, define when it should be selected, and use the instructions below. Bind the Dataverse MCP tools it needs.": "Mở Skills, tạo một skill có tên Account Planning, xác định khi nào skill nên được chọn và sử dụng các hướng dẫn bên dưới. Liên kết các công cụ Dataverse MCP mà skill cần.",
  [skillSetupEnglish]: skillSetupVietnamese,
  "Skills live in the **Build** tab (not Tools) — they're reusable instruction sets, distinct from Tools/MCP servers, which connect to external services.": "Skills nằm trong tab **Build** (không phải Tools) — đây là các bộ hướng dẫn có thể tái sử dụng, khác với Tools/MCP servers dùng để kết nối với các dịch vụ bên ngoài.",
  "Skill name": "Tên Skill",
  "Skill description": "Mô tả Skill",
  "Skill instruction": "Hướng dẫn cho Skill",
  "Preview and Test the result": "Xem trước và kiểm thử kết quả",
  "Open the **Preview** tab and test a matching request to confirm the skill activates and behaves as expected.": "Mở tab **Preview** và kiểm thử một yêu cầu phù hợp để xác nhận skill được kích hoạt và hoạt động như mong đợi.",
  "Test Prompt": "Prompt kiểm thử",
  "Remember my big bet account": "Ghi nhớ tài khoản Big Bet của tôi",
  "Enable Memory and tell the agent which accounts you frequently treat as Big Bets.": "Bật Memory và cho Agent biết những tài khoản nào bạn thường xem là Big Bets.",
  [memoryDisabledEnglish]: memoryDisabledVietnamese,
  "**Takeaway:** Without Memory, the account preference lives only inside a single conversation and is lost the moment you start a new one.": "**Điểm chính:** Khi không có Memory, tùy chọn tài khoản chỉ tồn tại trong một cuộc hội thoại và sẽ mất ngay khi bạn bắt đầu cuộc hội thoại mới.",
  "Prompt to set big bet account": "Prompt để thiết lập tài khoản Big Bet",
  "Prompt to ask agent": "Prompt để hỏi Agent",
  [memoryEnabledEnglish]: memoryEnabledVietnamese,
  "**Takeaway:** With Memory on, the preference persists across conversations, so the agent applies it automatically on future sessions.": "**Điểm chính:** Khi Memory bật, tùy chọn được duy trì qua các cuộc hội thoại để Agent tự động áp dụng trong những phiên sau.",
  "A quick wrap-up for Memory": "Tóm tắt nhanh về Memory",
  [memorySummaryEnglish]: memorySummaryVietnamese,
  "Now it's time to save our agent with **Memory** On.   Click \"**Save**\" and then \"**Publish**\" to publish th agent.": "Bây giờ hãy lưu Agent với **Memory** ở trạng thái On. Bấm \"**Save**\", sau đó bấm \"**Publish**\" để phát hành Agent.",
  "Enrich Customer 360 with Cowork": "Làm phong phú Customer 360 bằng Cowork",
  "Examine the existing Workflow": "Xem xét Workflow hiện có",
  "Create a workflow tool that passes the mentioned account name to Microsoft Cowork for public customer insights to enrich the account / customer 360.   Return structured findings and sources to the agent, then compare them with CRM facts.": "Tạo một công cụ workflow truyền tên tài khoản được đề cập đến Microsoft Cowork để thu thập thông tin công khai về khách hàng, qua đó làm phong phú Account / Customer 360. Trả về cho Agent các phát hiện có cấu trúc cùng nguồn tham khảo, sau đó so sánh chúng với dữ liệu CRM.",
  [coworkWorkflowEnglish]: coworkWorkflowVietnamese,
  "Workflow Name": "Tên Workflow",
  "Add Workflow Flow to Agent": "Thêm Workflow vào Agent",
  [addCoworkWorkflowEnglish]: addCoworkWorkflowVietnamese,
  "Workflow Tool Name": "Tên công cụ Workflow",
  "Workflow Tool Description": "Mô tả công cụ Workflow",
  "Workflow Tool - Input": "Công cụ Workflow - Đầu vào",
  "Test and oversee the output": "Kiểm thử và theo dõi đầu ra",
  [coworkTestEnglish]: coworkTestVietnamese,
  [coworkQuickChecksEnglish]: coworkQuickChecksVietnamese,
  "Enrich Customer 360 with M365 Copilot": "Làm phong phú Customer 360 bằng M365 Copilot",
  "Create a workflow tool that passes the mentioned account name to Microsoft Copilot 365 for public customer insights to enrich the account / customer 360.   Return structured findings and sources to the agent, then compare them with CRM facts.": "Tạo một công cụ workflow truyền tên tài khoản được đề cập đến Microsoft Copilot 365 để thu thập thông tin công khai về khách hàng, qua đó làm phong phú Account / Customer 360. Trả về cho Agent các phát hiện có cấu trúc cùng nguồn tham khảo, sau đó so sánh chúng với dữ liệu CRM.",
  [m365WorkflowEnglish]: m365WorkflowVietnamese,
  [addM365WorkflowEnglish]: addM365WorkflowVietnamese,
  [m365TestEnglish]: m365TestVietnamese,
  [m365QuickChecksEnglish]: m365QuickChecksVietnamese,
  "Use Dataverse MCP, Skills, Memory, and a CoWork workflow to build an account-aware assistant.": "Sử dụng Dataverse MCP, Skills, Memory và workflow CoWork để xây dựng một trợ lý am hiểu tài khoản.",
  "Create a reusable Account Planning skill.": "Tạo một Account Planning skill có thể tái sử dụng.",
  "Combine durable Memory with fresh external CoWork research.": "Kết hợp Memory bền vững với nghiên cứu bên ngoài mới nhất từ CoWork.",
  "In Tools, connect the facilitator-provided Dataverse MCP server with user authentication. Test: “Show my top 20 active accounts, ordered by the agreed account score.”": "Trong Tools, kết nối Dataverse MCP server do người hướng dẫn cung cấp bằng xác thực người dùng. Kiểm thử: “Show my top 20 active accounts, ordered by the agreed account score.”",
  "Define “my,” “active,” and the ranking field with your facilitator; do not let the model guess the business definition.": "Cùng người hướng dẫn xác định rõ “my”, “active” và trường xếp hạng; không để model tự suy đoán định nghĩa nghiệp vụ.",
  "Create the Account Planning skill": "Tạo Account Planning skill",
  "Remember Big Bet accounts": "Ghi nhớ các tài khoản Big Bet",
  "Enable Memory and tell the agent which accounts you frequently treat as Big Bets. Start a new session and ask for “my Big Bets” to verify durable recall.": "Bật Memory và cho Agent biết những tài khoản nào bạn thường xem là Big Bets. Bắt đầu một phiên mới và hỏi về “my Big Bets” để xác minh khả năng ghi nhớ lâu dài.",
  "Store preferences and stable identifiers, not confidential notes, credentials, or rapidly changing CRM facts.": "Chỉ lưu các tùy chọn và mã định danh ổn định; không lưu ghi chú mật, thông tin xác thực hoặc dữ liệu CRM thay đổi nhanh.",
  "Build the CoWork customer 360 workflow": "Xây dựng workflow CoWork Customer 360",
  "Create a workflow tool that passes the selected CRM account to CoWork for public research. Return structured findings and sources to the agent, then compare them with CRM facts.": "Tạo một công cụ workflow truyền tài khoản CRM đã chọn đến CoWork để nghiên cứu thông tin công khai. Trả về cho Agent các phát hiện có cấu trúc cùng nguồn tham khảo, sau đó so sánh chúng với dữ liệu CRM.",
}