import type { Lab } from '../../types'

const accountSkill = `# Skill: Build an account plan
When the user asks to plan for an account:
1. Resolve the account unambiguously with the Dataverse MCP server.
2. Retrieve the account profile, open opportunities, recent activities, stakeholders, and risks available to the current user.
3. Ask for the planning horizon and desired business outcome only if missing.
4. Produce: executive snapshot, customer priorities, relationship map, opportunity plays, risks, and a 30/60/90-day action plan.
5. Clearly label CRM facts, external research, and recommendations.
6. Do not expose records the signed-in user is not authorized to access.`

const coworkInput = `Research this account using public web sources and return an enhanced customer 360:

Account: {{Account.Name}}
Known domain: {{Account.Website}}
CRM context: {{AccountSummary}}

Find and summarize only verifiable information from the last 12 months:
- company strategy and executive priorities
- major announcements, acquisitions, and partnerships
- technology signals relevant to Microsoft
- material risks or market changes
- suggested conversation starters

Return source URL, publication date, and confidence for every external claim.`

export const lab02: Lab = {
  id: 'lab-02', number: 2, icon: 'database', duration: 60,
  title: { en: 'Bring in business context', zh: '接入业务上下文', ja: 'ビジネス コンテキストを追加', ko: '비즈니스 컨텍스트 연결', th: 'เพิ่มบริบททางธุรกิจ', hi: 'व्यावसायिक संदर्भ जोड़ें' },
  summary: { en: 'Use Dataverse MCP, Skills, Memory, and a CoWork workflow to build an account-aware assistant.', zh: '使用 Dataverse MCP、Skills、Memory 与 CoWork 工作流构建客户感知助手。', ja: 'Dataverse MCP、Skills、Memory、CoWork ワークフローでアカウント対応アシスタントを作ります。', ko: 'Dataverse MCP, Skills, Memory, CoWork 워크플로로 계정 인식 도우미를 만듭니다.', th: 'ใช้ Dataverse MCP, Skills, Memory และเวิร์กโฟลว์ CoWork เพื่อสร้างผู้ช่วยที่รับรู้ข้อมูลบัญชี', hi: 'Dataverse MCP, Skills, Memory और CoWork वर्कफ़्लो का उपयोग करके अकाउंट-अवेयर असिस्टेंट बनाएं।' },
  outcome: { en: 'An agent that retrieves your active accounts, remembers Big Bets, and creates a sourced customer 360.', zh: '一个可查询活跃客户、记忆 Big Bet 并生成有来源客户 360 的 Agent。', ja: 'アクティブ アカウントの取得、Big Bet の記憶、出典付き Customer 360 ができる Agent。', ko: '활성 계정 조회, Big Bet 기억, 출처 기반 고객 360을 제공하는 Agent.', th: 'Agent ที่ดึงบัญชีที่ใช้งานอยู่ จดจำ Big Bets และสร้าง Customer 360 ที่มีแหล่งอ้างอิง', hi: 'एक Agent जो आपके सक्रिय अकाउंट प्राप्त करता है, Big Bets याद रखता है, और स्रोत-सहित Customer 360 बनाता है।' },
  objectives: [
    { en: 'Connect Dataverse MCP with user-scoped access.', zh: '以用户范围权限连接 Dataverse MCP。', ja: 'ユーザー スコープのアクセスで Dataverse MCP に接続する。', ko: '사용자 범위 액세스로 Dataverse MCP를 연결합니다.', th: 'เชื่อมต่อ Dataverse MCP ด้วยการเข้าถึงตามขอบเขตผู้ใช้', hi: 'यूज़र-स्कोप्ड एक्सेस के साथ Dataverse MCP कनेक्ट करें।' },
    { en: 'Create a reusable Account Planning skill.', zh: '创建可复用的 Account Planning Skill。', ja: '再利用可能な Account Planning Skill を作成する。', ko: '재사용 가능한 Account Planning Skill을 만듭니다.', th: 'สร้าง Account Planning Skill ที่นำกลับมาใช้ซ้ำได้', hi: 'पुन: उपयोग योग्य Account Planning Skill बनाएं।' },
    { en: 'Combine durable Memory with fresh external CoWork research.', zh: '将持久 Memory 与最新 CoWork 外部调研结合。', ja: '永続 Memory と最新の CoWork 外部調査を組み合わせる。', ko: '지속형 Memory와 최신 CoWork 외부 조사를 결합합니다.', th: 'รวม Memory แบบถาวรเข้ากับการวิจัยภายนอกล่าสุดจาก CoWork', hi: 'टिकाऊ Memory को नए बाहरी CoWork शोध के साथ मिलाएं।' },
  ],
  prerequisites: [{ en: 'Complete Lab 1 and have read access to the facilitator Dataverse sample data.', zh: '完成 Lab 1，并拥有讲师 Dataverse 示例数据的读取权限。', ja: 'Lab 1 を完了し、Dataverse サンプル データの読み取り権限があること。', ko: 'Lab 1을 완료하고 Dataverse 샘플 데이터 읽기 권한이 있어야 합니다.', th: 'ทำ Lab 1 ให้เสร็จและมีสิทธิ์อ่านข้อมูลตัวอย่าง Dataverse ของผู้สอน', hi: 'Lab 1 पूरा करें और फैसिलिटेटर के Dataverse नमूना डेटा तक पढ़ने की पहुंच रखें।' }],
  steps: [
    { id: 'dataverse', imageKey: '01-dataverse-mcp', title: { en: 'Add Dataverse MCP', zh: '添加 Dataverse MCP', ja: 'Dataverse MCP を追加', ko: 'Dataverse MCP 추가', th: 'เพิ่ม Dataverse MCP', hi: 'Dataverse MCP जोड़ें' }, body: { en: 'In Tools, connect the facilitator-provided Dataverse MCP server with user authentication. Test: “Show my top 20 active accounts, ordered by the agreed account score.”', zh: '在 Tools 中以用户身份验证连接讲师提供的 Dataverse MCP。测试：“按约定客户评分列出我的前 20 个活跃客户。”', ja: 'Tools で Dataverse MCP にユーザー認証で接続し、「合意したスコア順に上位20のアクティブ アカウントを表示」とテストします。', ko: 'Tools에서 사용자 인증으로 Dataverse MCP를 연결하고 “합의된 계정 점수순으로 내 상위 20개 활성 계정 표시”를 테스트합니다.', th: 'ใน Tools ให้เชื่อมต่อ Dataverse MCP ที่ผู้สอนจัดให้ด้วยการยืนยันตัวตนของผู้ใช้ ทดสอบ: “แสดงบัญชีที่ใช้งานอยู่ 20 อันดับแรกของฉัน เรียงตามคะแนนบัญชีที่ตกลงกัน”', hi: 'Tools में, यूज़र प्रमाणीकरण के साथ फैसिलिटेटर द्वारा प्रदान किए गए Dataverse MCP सर्वर से कनेक्ट करें। परीक्षण: “सहमत अकाउंट स्कोर के क्रम में मेरे शीर्ष 20 सक्रिय अकाउंट दिखाएं।”' }, highlight: { en: 'Define “my,” “active,” and the ranking field with your facilitator; do not let the model guess the business definition.', zh: '请与讲师明确“我的”“活跃”及排序字段，不要让模型猜测业务定义。', ja: '「自分の」「アクティブ」「順位フィールド」の定義を講師と確認し、モデルに推測させないでください。', ko: '“내”, “활성”, 순위 필드를 진행자와 정의하고 모델이 추측하지 않게 하세요.', th: 'กำหนด “ของฉัน” “ใช้งานอยู่” และฟิลด์การจัดอันดับร่วมกับผู้สอน อย่าให้โมเดลเดาคำนิยามทางธุรกิจ', hi: '“मेरा,” “सक्रिय,” और रैंकिंग फ़ील्ड को अपने फैसिलिटेटर के साथ परिभाषित करें; मॉडल को व्यावसायिक परिभाषा का अनुमान न लगाने दें।' } },
    { id: 'skill', imageKey: '02-account-skill', title: { en: 'Create the Account Planning skill', zh: '创建 Account Planning Skill', ja: 'Account Planning Skill を作成', ko: 'Account Planning Skill 만들기', th: 'สร้าง Account Planning Skill', hi: 'Account Planning Skill बनाएं' }, body: { en: 'Open Skills, create a skill named Account Planning, define when it should be selected, and use the instructions below. Bind the Dataverse MCP tools it needs.', zh: '打开 Skills，新建名为 Account Planning 的 Skill，定义触发条件，使用下方指令，并绑定所需 Dataverse MCP 工具。', ja: 'Skills で Account Planning を作成し、選択条件と以下の指示を設定して Dataverse MCP ツールを関連付けます。', ko: 'Skills에서 Account Planning을 만들고 선택 조건과 아래 지침을 설정한 뒤 Dataverse MCP 도구를 연결합니다.', th: 'เปิด Skills สร้าง Skill ชื่อ Account Planning กำหนดเงื่อนไขการเลือกใช้ ใช้คำสั่งด้านล่าง และผูก Dataverse MCP tools ที่จำเป็น', hi: 'Skills खोलें, Account Planning नामक एक Skill बनाएं, इसे कब चुना जाए यह परिभाषित करें, और नीचे दिए निर्देशों का उपयोग करें। आवश्यक Dataverse MCP tools को बाइंड करें।' }, prompt: accountSkill },
    { id: 'memory', imageKey: '03-big-bet-memory', title: { en: 'Remember Big Bet accounts', zh: '记忆 Big Bet 客户', ja: 'Big Bet アカウントを記憶', ko: 'Big Bet 계정 기억', th: 'จดจำบัญชี Big Bet', hi: 'Big Bet अकाउंट याद रखें' }, body: { en: 'Enable Memory and tell the agent which accounts you frequently treat as Big Bets. Start a new session and ask for “my Big Bets” to verify durable recall.', zh: '启用 Memory，并告诉 Agent 哪些客户是你常用的 Big Bet。开始新会话并询问“我的 Big Bet”来验证持久记忆。', ja: 'Memory を有効にし、よく使う Big Bet アカウントを伝えます。新しいセッションで「my Big Bets」と質問して確認します。', ko: 'Memory를 활성화하고 자주 사용하는 Big Bet 계정을 알려 줍니다. 새 세션에서 “my Big Bets”를 물어 지속 기억을 확인합니다.', th: 'เปิดใช้งาน Memory และบอก Agent ว่าบัญชีใดที่คุณมักถือเป็น Big Bets เริ่มเซสชันใหม่และถาม “my Big Bets” เพื่อยืนยันการจดจำแบบถาวร', hi: 'Memory सक्षम करें और Agent को बताएं कि आप किन अकाउंट को अक्सर Big Bets मानते हैं। एक नया सत्र शुरू करें और टिकाऊ स्मृति सत्यापित करने के लिए “my Big Bets” पूछें।' }, highlight: { en: 'Store preferences and stable identifiers, not confidential notes, credentials, or rapidly changing CRM facts.', zh: '只存储偏好和稳定标识，不要存储机密备注、凭据或快速变化的 CRM 事实。', ja: '設定や安定した識別子のみを保存し、機密情報や変化する CRM 事実は保存しません。', ko: '환경 설정과 안정적인 식별자만 저장하고 기밀 메모, 자격 증명, 자주 변하는 CRM 사실은 저장하지 마세요.', th: 'จัดเก็บการตั้งค่าและตัวระบุที่คงที่ ไม่ใช่บันทึกลับ ข้อมูลรับรอง หรือข้อเท็จจริง CRM ที่เปลี่ยนแปลงบ่อย', hi: 'प्राथमिकताएं और स्थिर पहचानकर्ता संग्रहीत करें, गोपनीय नोट्स, क्रेडेंशियल, या तेज़ी से बदलते CRM तथ्य नहीं।' } },
    { id: 'cowork', imageKey: '04-cowork-workflow', title: { en: 'Build the CoWork customer 360 workflow', zh: '构建 CoWork 客户 360 工作流', ja: 'CoWork Customer 360 ワークフローを作成', ko: 'CoWork 고객 360 워크플로 만들기', th: 'สร้างเวิร์กโฟลว์ CoWork Customer 360', hi: 'CoWork Customer 360 वर्कफ़्लो बनाएं' }, body: { en: 'Create a workflow tool that passes the selected CRM account to CoWork for public research. Return structured findings and sources to the agent, then compare them with CRM facts.', zh: '创建工作流工具，将所选 CRM 客户传给 CoWork 进行公开信息调研，以结构化结果和来源返回 Agent，并与 CRM 事实比较。', ja: '選択した CRM アカウントを CoWork に渡して公開情報を調査し、構造化した結果と出典を Agent に返すワークフローを作成します。', ko: '선택한 CRM 계정을 CoWork에 전달해 공개 정보를 조사하고 구조화된 결과와 출처를 Agent에 반환하는 워크플로를 만듭니다.', th: 'สร้างเครื่องมือเวิร์กโฟลว์ที่ส่งบัญชี CRM ที่เลือกไปยัง CoWork เพื่อวิจัยข้อมูลสาธารณะ ส่งผลลัพธ์แบบมีโครงสร้างและแหล่งอ้างอิงกลับไปยัง Agent แล้วเปรียบเทียบกับข้อเท็จจริง CRM', hi: 'एक वर्कफ़्लो tool बनाएं जो चयनित CRM अकाउंट को सार्वजनिक शोध के लिए CoWork को भेजता है। संरचित निष्कर्ष और स्रोत Agent को लौटाएं, फिर उन्हें CRM तथ्यों से तुलना करें।' }, prompt: coworkInput },
  ],
}