import type { Locale, LocalizedText } from './types'

export const localeNames: Record<Locale, string> = {
  en: 'English',
  zh: '中文',
  ja: '日本語',
  ko: '한국어',
}

export const ui = {
  program: { en: 'AI Agent JumpStart 2', zh: 'AI Agent 动手起步营 2', ja: 'AI Agent JumpStart 2', ko: 'AI Agent JumpStart 2' },
  kicker: { en: 'Hands-on learning path', zh: '动手学习路径', ja: 'ハンズオン学習パス', ko: '실습 학습 경로' },
  progress: { en: 'Overall progress', zh: '总体进度', ja: '全体の進捗', ko: '전체 진행률' },
  lab: { en: 'Lab', zh: '实验', ja: 'ラボ', ko: '랩' },
  minutes: { en: 'min', zh: '分钟', ja: '分', ko: '분' },
  objectives: { en: 'Learning objectives', zh: '学习目标', ja: '学習目標', ko: '학습 목표' },
  prerequisites: { en: 'Before you begin', zh: '开始之前', ja: '開始する前に', ko: '시작하기 전에' },
  outcome: { en: 'You will build', zh: '你将构建', ja: '作成するもの', ko: '구축 결과' },
  step: { en: 'Step', zh: '步骤', ja: 'ステップ', ko: '단계' },
  highlight: { en: 'High light', zh: '重点提示', ja: '重要ポイント', ko: '핵심 포인트' },
  input: { en: 'Input to use', zh: '需要输入的内容', ja: '入力内容', ko: '입력할 내용' },
  copy: { en: 'Copy', zh: '复制', ja: 'コピー', ko: '복사' },
  copied: { en: 'Copied', zh: '已复制', ja: 'コピー済み', ko: '복사됨' },
  expand: { en: 'Expand input', zh: '展开输入', ja: '入力を展開', ko: '입력 펼치기' },
  collapse: { en: 'Collapse input', zh: '收起输入', ja: '入力を折りたたむ', ko: '입력 접기' },
  complete: { en: 'Mark step complete', zh: '标记步骤完成', ja: 'ステップを完了にする', ko: '단계 완료 표시' },
  completed: { en: 'Completed', zh: '已完成', ja: '完了', ko: '완료' },
  previous: { en: 'Previous', zh: '上一步', ja: '前へ', ko: '이전' },
  next: { en: 'Next', zh: '下一步', ja: '次へ', ko: '다음' },
  screenshot: { en: 'Screenshot placeholder', zh: '截图占位', ja: 'スクリーンショット予定', ko: '스크린샷 자리' },
  screenshotHint: { en: 'Replace this file with the localized product screenshot.', zh: '请用对应语言的产品截图替换此文件。', ja: '該当言語の製品スクリーンショットに置き換えてください。', ko: '해당 언어의 제품 스크린샷으로 교체하세요.' },
  overview: { en: 'Overview', zh: '概览', ja: '概要', ko: '개요' },
  guide: { en: 'Lab guide', zh: '实验手册', ja: 'ラボ ガイド', ko: '랩 가이드' },
  contents: { en: 'In this lab', zh: '本实验内容', ja: 'このラボの内容', ko: '이 랩의 내용' },
  page: { en: 'Page', zh: '页面', ja: 'ページ', ko: '페이지' },
  theme: { en: 'Toggle color theme', zh: '切换颜色主题', ja: 'カラーテーマを切替', ko: '색상 테마 전환' },
  menu: { en: 'Open lab navigation', zh: '打开实验导航', ja: 'ラボナビを開く', ko: '랩 탐색 열기' },
  close: { en: 'Close navigation', zh: '关闭导航', ja: 'ナビを閉じる', ko: '탐색 닫기' },
  collapseSidebar: { en: 'Collapse sidebar', zh: '收起侧栏', ja: 'サイドバーを閉じる', ko: '사이드바 접기' },
  expandSidebar: { en: 'Expand sidebar', zh: '展开侧栏', ja: 'サイドバーを開く', ko: '사이드바 펼치기' },
  language: { en: 'Language', zh: '语言', ja: '言語', ko: '언어' },
  workshopBranding: { en: 'Workshop branding', zh: '研讨会品牌设置', ja: 'ワークショップのブランディング', ko: '워크숍 브랜딩' },
  closeDialog: { en: 'Close', zh: '关闭', ja: '閉じる', ko: '닫기' },
  brandingHint: { en: 'Set a customer name or logo to co-brand this JumpStart. Save named workshops to reuse them anytime.', zh: '设置客户名称或徽标，为此 JumpStart 进行联合品牌设置。保存命名的研讨会以便随时复用。', ja: '顧客名またはロゴを設定して、この JumpStart を共同ブランディングできます。名前を付けたワークショップを保存すると、いつでも再利用できます。', ko: '고객 이름 또는 로고를 설정하여 이 JumpStart를 공동 브랜딩하세요. 이름을 지정한 워크숍을 저장해 언제든 재사용할 수 있습니다.' },
  hostName: { en: 'Host name', zh: '主办方名称', ja: '主催者名', ko: '주최자 이름' },
  hostLogoUrl: { en: 'Host logo URL', zh: '主办方徽标 URL', ja: '主催者ロゴの URL', ko: '주최자 로고 URL' },
  logoUrlHint: { en: 'https:// … (or upload below)', zh: 'https:// …（或在下方上传）', ja: 'https:// …（または下からアップロード）', ko: 'https:// … (또는 아래에서 업로드)' },
  uploadHostLogo: { en: 'Upload host logo', zh: '上传主办方徽标', ja: '主催者ロゴをアップロード', ko: '주최자 로고 업로드' },
  customerName: { en: 'Customer name', zh: '客户名称', ja: '顧客名', ko: '고객 이름' },
  customerNameHint: { en: 'e.g. Contoso', zh: '例如：Contoso', ja: '例: Contoso', ko: '예: Contoso' },
  customerLogoUrl: { en: 'Customer logo URL', zh: '客户徽标 URL', ja: '顧客ロゴの URL', ko: '고객 로고 URL' },
  uploadCustomerLogo: { en: 'Upload customer logo', zh: '上传客户徽标', ja: '顧客ロゴをアップロード', ko: '고객 로고 업로드' },
  removeLogo: { en: 'Remove', zh: '移除', ja: '削除', ko: '제거' },
  reset: { en: 'Reset', zh: '重置', ja: 'リセット', ko: '재설정' },
  saveToHistory: { en: 'Save to history', zh: '保存到历史记录', ja: '履歴に保存', ko: '기록에 저장' },
  apply: { en: 'Apply', zh: '应用', ja: '適用', ko: '적용' },
  applying: { en: 'Applying…', zh: '正在应用…', ja: '適用中…', ko: '적용 중…' },
  brandingPublished: { en: 'Applied and published to branding.json. Commit and push so everyone sees it.', zh: '已应用并发布到 branding.json。请提交并推送，以便所有人都能看到。', ja: 'branding.json に適用・公開しました。全員に表示するにはコミットしてプッシュしてください。', ko: 'branding.json에 적용 및 게시했습니다. 모두가 볼 수 있도록 커밋하고 푸시하세요.' },
  brandingOffline: { en: 'Applied locally. Run the app in dev and commit branding.json to share it.', zh: '已在本地应用。请在开发模式下运行应用并提交 branding.json 以进行共享。', ja: 'ローカルに適用しました。共有するには開発モードでアプリを実行し、branding.json をコミットしてください。', ko: '로컬에 적용했습니다. 공유하려면 개발 모드에서 앱을 실행하고 branding.json을 커밋하세요.' },
  workshopHistory: { en: 'Workshop history', zh: '研讨会历史记录', ja: 'ワークショップ履歴', ko: '워크숍 기록' },
  searchWorkshops: { en: 'Quick search saved workshops…', zh: '快速搜索已保存的研讨会…', ja: '保存したワークショップをすばやく検索…', ko: '저장된 워크숍 빠른 검색…' },
  noSavedWorkshops: { en: 'No saved workshops yet. Configure branding above, then select “Save to history.”', zh: '尚无已保存的研讨会。请先配置上方的品牌设置，然后选择“保存到历史记录”。', ja: '保存されたワークショップはまだありません。上でブランディングを設定し、「履歴に保存」を選択してください。', ko: '저장된 워크숍이 아직 없습니다. 위에서 브랜딩을 구성한 다음 “기록에 저장”을 선택하세요.' },
  noMatchingWorkshops: { en: 'No workshops match your search.', zh: '没有与搜索匹配的研讨会。', ja: '検索に一致するワークショップはありません。', ko: '검색과 일치하는 워크숍이 없습니다.' },
  loadWorkshop: { en: 'Load into the form', zh: '加载到表单', ja: 'フォームに読み込む', ko: '양식으로 불러오기' },
  deleteWorkshop: { en: 'Delete {name}', zh: '删除 {name}', ja: '{name} を削除', ko: '{name} 삭제' },
  savedWorkshop: { en: 'Saved “{name}”', zh: '已保存“{name}”', ja: '「{name}」を保存しました', ko: '“{name}” 저장됨' },
  updatedWorkshop: { en: 'Updated “{name}”', zh: '已更新“{name}”', ja: '「{name}」を更新しました', ko: '“{name}” 업데이트됨' },
  loadedWorkshop: { en: 'Loaded “{name}” — select Apply to use it', zh: '已加载“{name}”——选择“应用”以使用它', ja: '「{name}」を読み込みました。使用するには「適用」を選択してください', ko: '“{name}”을 불러왔습니다. 사용하려면 적용을 선택하세요' },
  maker: { en: 'Maker mode', zh: '创作者模式', ja: 'メーカー モード', ko: '메이커 모드' },
  makerUnlock: { en: 'Enter maker password', zh: '输入创作者密码', ja: 'メーカー パスワードを入力', ko: '메이커 암호 입력' },
  makerWrong: { en: 'Incorrect password', zh: '密码错误', ja: 'パスワードが違います', ko: '암호가 올바르지 않습니다' },
  unlock: { en: 'Unlock', zh: '解锁', ja: 'ロック解除', ko: '잠금 해제' },
  exitMaker: { en: 'Exit maker mode', zh: '退出创作者模式', ja: 'メーカー モードを終了', ko: '메이커 모드 종료' },
  editContent: { en: 'Edit content', zh: '编辑内容', ja: 'コンテンツを編集', ko: '콘텐츠 편집' },
  editingLanguage: { en: 'Editing language', zh: '编辑语言', ja: '編集言語', ko: '편집 언어' },
  copyEnglish: { en: 'Copy from English', zh: '从英文复制', ja: '英語からコピー', ko: '영어에서 복사' },
  save: { en: 'Save', zh: '保存', ja: '保存', ko: '저장' },
  saving: { en: 'Saving…', zh: '正在保存…', ja: '保存中…', ko: '저장 중…' },
  saved: { en: 'Saved', zh: '已保存', ja: '保存しました', ko: '저장됨' },
  publish: { en: 'Publish to GitHub', zh: '发布到 GitHub', ja: 'GitHub に公開', ko: 'GitHub에 게시' },
  publishing: { en: 'Publishing…', zh: '正在发布…', ja: '公開中…', ko: '게시 중…' },
  published: { en: 'Published', zh: '已发布', ja: '公開しました', ko: '게시됨' },
  discard: { en: 'Discard changes', zh: '放弃更改', ja: '変更を破棄', ko: '변경 취소' },
  addLab: { en: 'Add lab', zh: '添加实验', ja: 'ラボを追加', ko: '랩 추가' },
  addStep: { en: 'Add step', zh: '添加步骤', ja: 'ステップを追加', ko: '단계 추가' },
  addPage: { en: 'Add page', zh: '添加页面', ja: 'ページを追加', ko: '페이지 추가' },
  addParagraph: { en: 'Add paragraph', zh: '添加段落', ja: '段落を追加', ko: '단락 추가' },
  addObjective: { en: 'Add objective', zh: '添加目标', ja: '目標を追加', ko: '목표 추가' },
  addPrerequisite: { en: 'Add prerequisite', zh: '添加前提', ja: '前提条件を追加', ko: '전제 조건 추가' },
  addImage: { en: 'Add screenshot key', zh: '添加截图键', ja: 'スクショ キーを追加', ko: '스크린샷 키 추가' },
  remove: { en: 'Remove', zh: '删除', ja: '削除', ko: '삭제' },
  moveUp: { en: 'Move up', zh: '上移', ja: '上へ', ko: '위로' },
  moveDown: { en: 'Move down', zh: '下移', ja: '下へ', ko: '아래로' },
  labTitle: { en: 'Lab title', zh: '实验标题', ja: 'ラボ タイトル', ko: '랩 제목' },
  labSummary: { en: 'Summary', zh: '摘要', ja: '概要', ko: '요약' },
  labOutcome: { en: 'Outcome', zh: '成果', ja: '成果', ko: '결과' },
  labIcon: { en: 'Icon', zh: '图标', ja: 'アイコン', ko: '아이콘' },
  labDuration: { en: 'Duration (min)', zh: '时长（分钟）', ja: '所要時間（分）', ko: '소요 시간(분)' },
  stepTitle: { en: 'Step title (Markdown)', zh: '步骤标题（Markdown）', ja: 'ステップ タイトル（Markdown）', ko: '단계 제목(Markdown)' },
  pageTitle: { en: 'Page title (Markdown, optional)', zh: '页面标题（Markdown，可选）', ja: 'ページ タイトル（Markdown・任意）', ko: '페이지 제목(Markdown, 선택)' },
  fieldHighlight: { en: 'Highlight Markdown (optional)', zh: '重点提示 Markdown（可选）', ja: '重要ポイント Markdown（任意）', ko: '핵심 포인트 Markdown(선택)' },
  fieldPrompt: { en: 'Input / prompt content (same for all languages)', zh: '输入/提示内容（所有语言相同）', ja: '入力/プロンプト内容（全言語共通）', ko: '입력/프롬프트 내용(모든 언어 공통)' },
  fieldPromptTitle: { en: 'Input title (e.g. Agent instruction, Skill)', zh: '输入标题（例如：Agent 指令、Skill）', ja: '入力タイトル（例：Agent 指示、Skill）', ko: '입력 제목(예: Agent 지침, Skill)' },
  addPrompt: { en: 'Add input / prompt', zh: '添加输入/提示', ja: '入力/プロンプトを追加', ko: '입력/프롬프트 추가' },
  promptDefaultTitle: { en: 'Instructions / Input', zh: '说明/输入', ja: '指示/入力', ko: '지침/입력' },
  publishHint: { en: 'Save writes labs.json locally; Publish commits and pushes it to GitHub.', zh: '保存会写入本地 labs.json；发布会提交并推送到 GitHub。', ja: '保存はローカルの labs.json に書き込み、公開は GitHub にコミット & プッシュします。', ko: '저장은 로컬 labs.json에 기록하고, 게시는 GitHub에 커밋 및 푸시합니다.' },
  fallbackNote: { en: 'Empty non-English fields fall back to English when learners view the lab.', zh: '非英文字段为空时，学员查看实验时将回退为英文。', ja: '英語以外が空の場合、受講者には英語が表示されます。', ko: '영어 외 필드가 비어 있으면 학습자에게 영어로 표시됩니다.' },
} satisfies Record<string, LocalizedText>

export const text = (value: LocalizedText | undefined, locale: Locale) => {
  if (!value) return ''
  return value[locale]?.trim() ? value[locale] : value.en
}