import type { Locale, LocalizedText } from './types'

export const localeNames: Record<Locale, string> = {
  en: 'English',
  zh: '中文',
  ja: '日本語',
  ko: '한국어',
  th: 'ไทย',
  hi: 'हिन्दी',
}

export const ui = {
  program: { en: 'AI Agent JumpStart 2', zh: 'AI Agent 动手起步营 2', ja: 'AI Agent JumpStart 2', ko: 'AI Agent JumpStart 2', th: 'AI Agent JumpStart 2', hi: 'AI Agent JumpStart 2' },
  kicker: { en: 'Hands-on learning path', zh: '动手学习路径', ja: 'ハンズオン学習パス', ko: '실습 학습 경로', th: 'เส้นทางการเรียนรู้แบบลงมือทำ', hi: 'हैंड्स-ऑन लर्निंग पाथ' },
  progress: { en: 'Overall progress', zh: '总体进度', ja: '全体の進捗', ko: '전체 진행률', th: 'ความคืบหน้าโดยรวม', hi: 'कुल प्रगति' },
  lab: { en: 'Lab', zh: '实验', ja: 'ラボ', ko: '랩', th: 'แล็บ', hi: 'लैब' },
  minutes: { en: 'min', zh: '分钟', ja: '分', ko: '분', th: 'นาที', hi: 'मिनट' },
  objectives: { en: 'Learning objectives', zh: '学习目标', ja: '学習目標', ko: '학습 목표', th: 'วัตถุประสงค์การเรียนรู้', hi: 'सीखने के उद्देश्य' },
  prerequisites: { en: 'Before you begin', zh: '开始之前', ja: '開始する前に', ko: '시작하기 전에', th: 'ก่อนเริ่มต้น', hi: 'शुरू करने से पहले' },
  outcome: { en: 'You will build', zh: '你将构建', ja: '作成するもの', ko: '구축 결과', th: 'สิ่งที่คุณจะสร้าง', hi: 'आप क्या बनाएंगे' },
  step: { en: 'Step', zh: '步骤', ja: 'ステップ', ko: '단계', th: 'ขั้นตอน', hi: 'चरण' },
  highlight: { en: 'High light', zh: '重点提示', ja: '重要ポイント', ko: '핵심 포인트', th: 'จุดสำคัญ', hi: 'मुख्य बिंदु' },
  input: { en: 'Input to use', zh: '需要输入的内容', ja: '入力内容', ko: '입력할 내용', th: 'ข้อมูลที่ต้องใช้', hi: 'उपयोग करने के लिए इनपुट' },
  copy: { en: 'Copy', zh: '复制', ja: 'コピー', ko: '복사', th: 'คัดลอก', hi: 'कॉपी' },
  copied: { en: 'Copied', zh: '已复制', ja: 'コピー済み', ko: '복사됨', th: 'คัดลอกแล้ว', hi: 'कॉपी किया गया' },
  expand: { en: 'Expand input', zh: '展开输入', ja: '入力を展開', ko: '입력 펼치기', th: 'ขยายอินพุต', hi: 'इनपुट विस्तृत करें' },
  collapse: { en: 'Collapse input', zh: '收起输入', ja: '入力を折りたたむ', ko: '입력 접기', th: 'ย่ออินพุต', hi: 'इनपुट संक्षिप्त करें' },
  complete: { en: 'Mark step complete', zh: '标记步骤完成', ja: 'ステップを完了にする', ko: '단계 완료 표시', th: 'ทำเครื่องหมายว่าเสร็จสิ้น', hi: 'चरण पूर्ण चिह्नित करें' },
  completed: { en: 'Completed', zh: '已完成', ja: '完了', ko: '완료', th: 'เสร็จสิ้น', hi: 'पूर्ण' },
  previous: { en: 'Previous', zh: '上一步', ja: '前へ', ko: '이전', th: 'ก่อนหน้า', hi: 'पिछला' },
  next: { en: 'Next', zh: '下一步', ja: '次へ', ko: '다음', th: 'ถัดไป', hi: 'अगला' },
  screenshot: { en: 'Screenshot placeholder', zh: '截图占位', ja: 'スクリーンショット予定', ko: '스크린샷 자리', th: 'ตัวอย่างภาพหน้าจอ', hi: 'स्क्रीनशॉट प्लेसहोल्डर' },
  screenshotHint: { en: 'Replace this file with the localized product screenshot.', zh: '请用对应语言的产品截图替换此文件。', ja: '該当言語の製品スクリーンショットに置き換えてください。', ko: '해당 언어의 제품 스크린샷으로 교체하세요.', th: 'แทนที่ไฟล์นี้ด้วยภาพหน้าจอผลิตภัณฑ์ในภาษาที่ต้องการ', hi: 'इस फ़ाइल को स्थानीयकृत उत्पाद स्क्रीनशॉट से बदलें।' },
  overview: { en: 'Overview', zh: '概览', ja: '概要', ko: '개요', th: 'ภาพรวม', hi: 'अवलोकन' },
  guide: { en: 'Lab guide', zh: '实验手册', ja: 'ラボ ガイド', ko: '랩 가이드', th: 'คู่มือแล็บ', hi: 'लैब गाइड' },
  contents: { en: 'In this lab', zh: '本实验内容', ja: 'このラボの内容', ko: '이 랩의 내용', th: 'ในแล็บนี้', hi: 'इस लैब में' },
  page: { en: 'Page', zh: '页面', ja: 'ページ', ko: '페이지', th: 'หน้า', hi: 'पृष्ठ' },
  theme: { en: 'Toggle color theme', zh: '切换颜色主题', ja: 'カラーテーマを切替', ko: '색상 테마 전환', th: 'สลับธีมสี', hi: 'रंग थीम टॉगल करें' },
  menu: { en: 'Open lab navigation', zh: '打开实验导航', ja: 'ラボナビを開く', ko: '랩 탐색 열기', th: 'เปิดการนำทางแล็บ', hi: 'लैब नेविगेशन खोलें' },
  close: { en: 'Close navigation', zh: '关闭导航', ja: 'ナビを閉じる', ko: '탐색 닫기', th: 'ปิดการนำทาง', hi: 'नेविगेशन बंद करें' },
  collapseSidebar: { en: 'Collapse sidebar', zh: '收起侧栏', ja: 'サイドバーを閉じる', ko: '사이드바 접기', th: 'ย่อแถบด้านข้าง', hi: 'साइडबार संक्षिप्त करें' },
  expandSidebar: { en: 'Expand sidebar', zh: '展开侧栏', ja: 'サイドバーを開く', ko: '사이드바 펼치기', th: 'ขยายแถบด้านข้าง', hi: 'साइडबार विस्तृत करें' },
  language: { en: 'Language', zh: '语言', ja: '言語', ko: '언어', th: 'ภาษา', hi: 'भाषा' },
  workshopBranding: { en: 'Workshop branding', zh: '研讨会品牌设置', ja: 'ワークショップのブランディング', ko: '워크숍 브랜딩', th: 'การสร้างแบรนด์เวิร์กช็อป', hi: 'वर्कशॉप ब्रांडिंग' },
  closeDialog: { en: 'Close', zh: '关闭', ja: '閉じる', ko: '닫기', th: 'ปิด', hi: 'बंद करें' },
  brandingHint: { en: 'Set a customer name or logo to co-brand this JumpStart. Save named workshops to reuse them anytime.', zh: '设置客户名称或徽标，为此 JumpStart 进行联合品牌设置。保存命名的研讨会以便随时复用。', ja: '顧客名またはロゴを設定して、この JumpStart を共同ブランディングできます。名前を付けたワークショップを保存すると、いつでも再利用できます。', ko: '고객 이름 또는 로고를 설정하여 이 JumpStart를 공동 브랜딩하세요. 이름을 지정한 워크숍을 저장해 언제든 재사용할 수 있습니다.', th: 'ตั้งชื่อหรือโลโก้ลูกค้าเพื่อร่วมสร้างแบรนด์ JumpStart นี้ บันทึกเวิร์กช็อปที่ตั้งชื่อไว้เพื่อนำกลับมาใช้ได้ทุกเมื่อ', hi: 'इस JumpStart को को-ब्रांड करने के लिए ग्राहक का नाम या लोगो सेट करें। नामित वर्कशॉप सहेजें और कभी भी दोबारा उपयोग करें।' },
  hostName: { en: 'Host name', zh: '主办方名称', ja: '主催者名', ko: '주최자 이름', th: 'ชื่อผู้จัด', hi: 'होस्ट का नाम' },
  hostLogoUrl: { en: 'Host logo URL', zh: '主办方徽标 URL', ja: '主催者ロゴの URL', ko: '주최자 로고 URL', th: 'URL โลโก้ผู้จัด', hi: 'होस्ट लोगो URL' },
  logoUrlHint: { en: 'https:// … (or upload below)', zh: 'https:// …（或在下方上传）', ja: 'https:// …（または下からアップロード）', ko: 'https:// … (또는 아래에서 업로드)', th: 'https:// … (หรืออัปโหลดด้านล่าง)', hi: 'https:// … (या नीचे अपलोड करें)' },
  uploadHostLogo: { en: 'Upload host logo', zh: '上传主办方徽标', ja: '主催者ロゴをアップロード', ko: '주최자 로고 업로드', th: 'อัปโหลดโลโก้ผู้จัด', hi: 'होस्ट लोगो अपलोड करें' },
  customerName: { en: 'Customer name', zh: '客户名称', ja: '顧客名', ko: '고객 이름', th: 'ชื่อลูกค้า', hi: 'ग्राहक का नाम' },
  customerNameHint: { en: 'e.g. Contoso', zh: '例如：Contoso', ja: '例: Contoso', ko: '예: Contoso', th: 'เช่น Contoso', hi: 'उदा. Contoso' },
  customerLogoUrl: { en: 'Customer logo URL', zh: '客户徽标 URL', ja: '顧客ロゴの URL', ko: '고객 로고 URL', th: 'URL โลโก้ลูกค้า', hi: 'ग्राहक लोगो URL' },
  uploadCustomerLogo: { en: 'Upload customer logo', zh: '上传客户徽标', ja: '顧客ロゴをアップロード', ko: '고객 로고 업로드', th: 'อัปโหลดโลโก้ลูกค้า', hi: 'ग्राहक लोगो अपलोड करें' },
  removeLogo: { en: 'Remove', zh: '移除', ja: '削除', ko: '제거', th: 'ลบ', hi: 'हटाएं' },
  reset: { en: 'Reset', zh: '重置', ja: 'リセット', ko: '재설정', th: 'รีเซ็ต', hi: 'रीसेट' },
  saveToHistory: { en: 'Save to history', zh: '保存到历史记录', ja: '履歴に保存', ko: '기록에 저장', th: 'บันทึกลงประวัติ', hi: 'इतिहास में सहेजें' },
  apply: { en: 'Apply', zh: '应用', ja: '適用', ko: '적용', th: 'ใช้งาน', hi: 'लागू करें' },
  applying: { en: 'Applying…', zh: '正在应用…', ja: '適用中…', ko: '적용 중…', th: 'กำลังใช้งาน…', hi: 'लागू किया जा रहा है…' },
  brandingPublished: { en: 'Applied and published to branding.json. Commit and push so everyone sees it.', zh: '已应用并发布到 branding.json。请提交并推送，以便所有人都能看到。', ja: 'branding.json に適用・公開しました。全員に表示するにはコミットしてプッシュしてください。', ko: 'branding.json에 적용 및 게시했습니다. 모두가 볼 수 있도록 커밋하고 푸시하세요.', th: 'ใช้งานและเผยแพร่ไปยัง branding.json แล้ว คอมมิตและพุชเพื่อให้ทุกคนเห็น', hi: 'branding.json पर लागू और प्रकाशित किया गया। सभी को दिखाने के लिए commit और push करें।' },
  brandingOffline: { en: 'Applied locally. Run the app in dev and commit branding.json to share it.', zh: '已在本地应用。请在开发模式下运行应用并提交 branding.json 以进行共享。', ja: 'ローカルに適用しました。共有するには開発モードでアプリを実行し、branding.json をコミットしてください。', ko: '로컬에 적용했습니다. 공유하려면 개발 모드에서 앱을 실행하고 branding.json을 커밋하세요.', th: 'ใช้งานในเครื่องแล้ว รันแอปในโหมด dev และคอมมิต branding.json เพื่อแชร์', hi: 'स्थानीय रूप से लागू किया गया। साझा करने के लिए ऐप को dev में चलाएं और branding.json commit करें।' },
  workshopHistory: { en: 'Workshop history', zh: '研讨会历史记录', ja: 'ワークショップ履歴', ko: '워크숍 기록', th: 'ประวัติเวิร์กช็อป', hi: 'वर्कशॉप इतिहास' },
  searchWorkshops: { en: 'Quick search saved workshops…', zh: '快速搜索已保存的研讨会…', ja: '保存したワークショップをすばやく検索…', ko: '저장된 워크숍 빠른 검색…', th: 'ค้นหาเวิร์กช็อปที่บันทึกไว้อย่างรวดเร็ว…', hi: 'सहेजे गए वर्कशॉप त्वरित खोजें…' },
  noSavedWorkshops: { en: 'No saved workshops yet. Configure branding above, then select “Save to history.”', zh: '尚无已保存的研讨会。请先配置上方的品牌设置，然后选择“保存到历史记录”。', ja: '保存されたワークショップはまだありません。上でブランディングを設定し、「履歴に保存」を選択してください。', ko: '저장된 워크숍이 아직 없습니다. 위에서 브랜딩을 구성한 다음 “기록에 저장”을 선택하세요.', th: 'ยังไม่มีเวิร์กช็อปที่บันทึกไว้ กำหนดค่าแบรนด์ด้านบน แล้วเลือก “บันทึกลงประวัติ”', hi: 'अभी तक कोई सहेजा हुआ वर्कशॉप नहीं। ऊपर ब्रांडिंग कॉन्फ़िगर करें, फिर “इतिहास में सहेजें” चुनें।' },
  noMatchingWorkshops: { en: 'No workshops match your search.', zh: '没有与搜索匹配的研讨会。', ja: '検索に一致するワークショップはありません。', ko: '검색과 일치하는 워크숍이 없습니다.', th: 'ไม่มีเวิร์กช็อปที่ตรงกับการค้นหา', hi: 'आपकी खोज से कोई वर्कशॉप मेल नहीं खाता।' },
  loadWorkshop: { en: 'Load into the form', zh: '加载到表单', ja: 'フォームに読み込む', ko: '양식으로 불러오기', th: 'โหลดลงในฟอร์ม', hi: 'फ़ॉर्म में लोड करें' },
  deleteWorkshop: { en: 'Delete {name}', zh: '删除 {name}', ja: '{name} を削除', ko: '{name} 삭제', th: 'ลบ {name}', hi: '{name} हटाएं' },
  savedWorkshop: { en: 'Saved “{name}”', zh: '已保存“{name}”', ja: '「{name}」を保存しました', ko: '“{name}” 저장됨', th: 'บันทึก “{name}” แล้ว', hi: '“{name}” सहेजा गया' },
  updatedWorkshop: { en: 'Updated “{name}”', zh: '已更新“{name}”', ja: '「{name}」を更新しました', ko: '“{name}” 업데이트됨', th: 'อัปเดต “{name}” แล้ว', hi: '“{name}” अपडेट किया गया' },
  loadedWorkshop: { en: 'Loaded “{name}” — select Apply to use it', zh: '已加载“{name}”——选择“应用”以使用它', ja: '「{name}」を読み込みました。使用するには「適用」を選択してください', ko: '“{name}”을 불러왔습니다. 사용하려면 적용을 선택하세요', th: 'โหลด “{name}” แล้ว — เลือกใช้งานเพื่อใช้', hi: '“{name}” लोड किया गया — उपयोग के लिए Apply चुनें' },
  maker: { en: 'Maker mode', zh: '创作者模式', ja: 'メーカー モード', ko: '메이커 모드', th: 'โหมดผู้สร้าง', hi: 'मेकर मोड' },
  makerUnlock: { en: 'Enter maker password', zh: '输入创作者密码', ja: 'メーカー パスワードを入力', ko: '메이커 암호 입력', th: 'ป้อนรหัสผ่านผู้สร้าง', hi: 'मेकर पासवर्ड दर्ज करें' },
  makerWrong: { en: 'Incorrect password', zh: '密码错误', ja: 'パスワードが違います', ko: '암호가 올바르지 않습니다', th: 'รหัสผ่านไม่ถูกต้อง', hi: 'गलत पासवर्ड' },
  reauthHint: { en: 'Your maker session expired. Enter the password to keep editing and save.', zh: '创作者会话已过期。请输入密码以继续编辑并保存。', ja: 'メーカー セッションの有効期限が切れました。編集と保存を続けるにはパスワードを入力してください。', ko: '메이커 세션이 만료되었습니다. 계속 편집하고 저장하려면 암호를 입력하세요.', th: 'เซสชันผู้สร้างหมดอายุ ป้อนรหัสผ่านเพื่อแก้ไขและบันทึกต่อ', hi: 'आपका मेकर सत्र समाप्त हो गया। संपादन और सहेजना जारी रखने के लिए पासवर्ड दर्ज करें।' },
  unlock: { en: 'Unlock', zh: '解锁', ja: 'ロック解除', ko: '잠금 해제', th: 'ปลดล็อก', hi: 'अनलॉक' },
  exitMaker: { en: 'Exit maker mode', zh: '退出创作者模式', ja: 'メーカー モードを終了', ko: '메이커 모드 종료', th: 'ออกจากโหมดผู้สร้าง', hi: 'मेकर मोड से बाहर निकलें' },
  editContent: { en: 'Edit content', zh: '编辑内容', ja: 'コンテンツを編集', ko: '콘텐츠 편집', th: 'แก้ไขเนื้อหา', hi: 'सामग्री संपादित करें' },
  editingLanguage: { en: 'Editing language', zh: '编辑语言', ja: '編集言語', ko: '편집 언어', th: 'ภาษาที่แก้ไข', hi: 'संपादन भाषा' },
  copyEnglish: { en: 'Copy from English', zh: '从英文复制', ja: '英語からコピー', ko: '영어에서 복사', th: 'คัดลอกจากภาษาอังกฤษ', hi: 'अंग्रेज़ी से कॉपी करें' },
  save: { en: 'Save', zh: '保存', ja: '保存', ko: '저장', th: 'บันทึก', hi: 'सहेजें' },
  saving: { en: 'Saving…', zh: '正在保存…', ja: '保存中…', ko: '저장 중…', th: 'กำลังบันทึก…', hi: 'सहेजा जा रहा है…' },
  saved: { en: 'Saved', zh: '已保存', ja: '保存しました', ko: '저장됨', th: 'บันทึกแล้ว', hi: 'सहेजा गया' },
  publish: { en: 'Publish to GitHub', zh: '发布到 GitHub', ja: 'GitHub に公開', ko: 'GitHub에 게시', th: 'เผยแพร่ไปยัง GitHub', hi: 'GitHub पर प्रकाशित करें' },
  publishing: { en: 'Publishing…', zh: '正在发布…', ja: '公開中…', ko: '게시 중…', th: 'กำลังเผยแพร่…', hi: 'प्रकाशित किया जा रहा है…' },
  published: { en: 'Published', zh: '已发布', ja: '公開しました', ko: '게시됨', th: 'เผยแพร่แล้ว', hi: 'प्रकाशित' },
  discard: { en: 'Discard changes', zh: '放弃更改', ja: '変更を破棄', ko: '변경 취소', th: 'ยกเลิกการเปลี่ยนแปลง', hi: 'परिवर्तन खारिज करें' },
  addLab: { en: 'Add lab', zh: '添加实验', ja: 'ラボを追加', ko: '랩 추가', th: 'เพิ่มแล็บ', hi: 'लैब जोड़ें' },
  addStep: { en: 'Add step', zh: '添加步骤', ja: 'ステップを追加', ko: '단계 추가', th: 'เพิ่มขั้นตอน', hi: 'चरण जोड़ें' },
  addPage: { en: 'Add page', zh: '添加页面', ja: 'ページを追加', ko: '페이지 추가', th: 'เพิ่มหน้า', hi: 'पृष्ठ जोड़ें' },
  addParagraph: { en: 'Add paragraph', zh: '添加段落', ja: '段落を追加', ko: '단락 추가', th: 'เพิ่มย่อหน้า', hi: 'अनुच्छेद जोड़ें' },
  addObjective: { en: 'Add objective', zh: '添加目标', ja: '目標を追加', ko: '목표 추가', th: 'เพิ่มวัตถุประสงค์', hi: 'उद्देश्य जोड़ें' },
  addPrerequisite: { en: 'Add prerequisite', zh: '添加前提', ja: '前提条件を追加', ko: '전제 조건 추가', th: 'เพิ่มข้อกำหนดเบื้องต้น', hi: 'पूर्वापेक्षा जोड़ें' },
  addImage: { en: 'Add screenshot key', zh: '添加截图键', ja: 'スクショ キーを追加', ko: '스크린샷 키 추가', th: 'เพิ่มคีย์ภาพหน้าจอ', hi: 'स्क्रीनशॉट कुंजी जोड़ें' },
  remove: { en: 'Remove', zh: '删除', ja: '削除', ko: '삭제', th: 'ลบ', hi: 'हटाएं' },
  moveUp: { en: 'Move up', zh: '上移', ja: '上へ', ko: '위로', th: 'เลื่อนขึ้น', hi: 'ऊपर ले जाएं' },
  moveDown: { en: 'Move down', zh: '下移', ja: '下へ', ko: '아래로', th: 'เลื่อนลง', hi: 'नीचे ले जाएं' },
  labTitle: { en: 'Lab title', zh: '实验标题', ja: 'ラボ タイトル', ko: '랩 제목', th: 'ชื่อแล็บ', hi: 'लैब शीर्षक' },
  labSummary: { en: 'Summary', zh: '摘要', ja: '概要', ko: '요약', th: 'สรุป', hi: 'सारांश' },
  labOutcome: { en: 'Outcome', zh: '成果', ja: '成果', ko: '결과', th: 'ผลลัพธ์', hi: 'परिणाम' },
  labIcon: { en: 'Icon', zh: '图标', ja: 'アイコン', ko: '아이콘', th: 'ไอคอน', hi: 'आइकन' },
  labDuration: { en: 'Duration (min)', zh: '时长（分钟）', ja: '所要時間（分）', ko: '소요 시간(분)', th: 'ระยะเวลา (นาที)', hi: 'अवधि (मिनट)' },
  labVisibility: { en: 'Visibility', zh: '可见性', ja: '公開設定', ko: '공개 설정', th: 'การมองเห็น', hi: 'दृश्यता' },
  isPublic: { en: 'Public', zh: '公开', ja: '公開', ko: '공개', th: 'สาธารณะ', hi: 'सार्वजनिक' },
  isPrivate: { en: 'Private (build only)', zh: '私有（仅构建）', ja: '非公開（作成のみ）', ko: '비공개(빌드 전용)', th: 'ส่วนตัว (สร้างเท่านั้น)', hi: 'निजी (केवल बिल्ड)' },
  publicLab: { en: 'Public — visible to workshop users when published, and counts toward progress.', zh: '公开——发布后研讨会用户可见，并计入进度。', ja: '公開 — 公開後にワークショップ利用者に表示され、進捗にカウントされます。', ko: '공개 — 게시 후 워크숍 사용자에게 표시되며 진행률에 포함됩니다.', th: 'สาธารณะ — ผู้ใช้เวิร์กช็อปเห็นเมื่อเผยแพร่ และนับรวมในความคืบหน้า', hi: 'सार्वजनिक — प्रकाशित होने पर वर्कशॉप उपयोगकर्ताओं को दिखता है और प्रगति में गिना जाता है।' },
  privateLab: { en: 'Private — build-only draft. Hidden from the published workshop and excluded from progress.', zh: '私有——仅用于构建的草稿。不会出现在已发布的研讨会中，也不计入进度。', ja: '非公開 — 作成専用の下書き。公開されたワークショップには表示されず、進捗にも含まれません。', ko: '비공개 — 빌드 전용 초안입니다. 게시된 워크숍에서 숨겨지고 진행률에서 제외됩니다.', th: 'ส่วนตัว — ฉบับร่างสำหรับสร้างเท่านั้น ซ่อนจากเวิร์กช็อปที่เผยแพร่และไม่นับรวมในความคืบหน้า', hi: 'निजी — केवल-बिल्ड ड्राफ़्ट। प्रकाशित वर्कशॉप से छिपा और प्रगति से बाहर।' },
  privateBadge: { en: 'Private', zh: '私有', ja: '非公開', ko: '비공개', th: 'ส่วนตัว', hi: 'निजी' },
  stepTitle: { en: 'Step title (Markdown)', zh: '步骤标题（Markdown）', ja: 'ステップ タイトル（Markdown）', ko: '단계 제목(Markdown)', th: 'ชื่อขั้นตอน (Markdown)', hi: 'चरण शीर्षक (Markdown)' },
  pageTitle: { en: 'Page title (Markdown, optional)', zh: '页面标题（Markdown，可选）', ja: 'ページ タイトル（Markdown・任意）', ko: '페이지 제목(Markdown, 선택)', th: 'ชื่อหน้า (Markdown, ไม่บังคับ)', hi: 'पृष्ठ शीर्षक (Markdown, वैकल्पिक)' },
  fieldHighlight: { en: 'Highlight Markdown (optional)', zh: '重点提示 Markdown（可选）', ja: '重要ポイント Markdown（任意）', ko: '핵심 포인트 Markdown(선택)', th: 'จุดสำคัญ Markdown (ไม่บังคับ)', hi: 'हाइलाइट Markdown (वैकल्पिक)' },
  fieldPrompt: { en: 'Input / prompt content (same for all languages)', zh: '输入/提示内容（所有语言相同）', ja: '入力/プロンプト内容（全言語共通）', ko: '입력/프롬프트 내용(모든 언어 공통)', th: 'เนื้อหาอินพุต/พรอมป์ต์ (เหมือนกันทุกภาษา)', hi: 'इनपुट / प्रॉम्प्ट सामग्री (सभी भाषाओं के लिए समान)' },
  fieldPromptTitle: { en: 'Input title (e.g. Agent instruction, Skill)', zh: '输入标题（例如：Agent 指令、Skill）', ja: '入力タイトル（例：Agent 指示、Skill）', ko: '입력 제목(예: Agent 지침, Skill)', th: 'ชื่ออินพุต (เช่น Agent instruction, Skill)', hi: 'इनपुट शीर्षक (उदा. Agent instruction, Skill)' },
  addPrompt: { en: 'Add input / prompt', zh: '添加输入/提示', ja: '入力/プロンプトを追加', ko: '입력/프롬프트 추가', th: 'เพิ่มอินพุต/พรอมป์ต์', hi: 'इनपुट / प्रॉम्प्ट जोड़ें' },
  promptDefaultTitle: { en: 'Instructions / Input', zh: '说明/输入', ja: '指示/入力', ko: '지침/입력', th: 'คำแนะนำ/อินพุต', hi: 'निर्देश / इनपुट' },
  publishHint: { en: 'Save writes labs.json locally; Publish commits and pushes it to GitHub.', zh: '保存会写入本地 labs.json；发布会提交并推送到 GitHub。', ja: '保存はローカルの labs.json に書き込み、公開は GitHub にコミット & プッシュします。', ko: '저장은 로컬 labs.json에 기록하고, 게시는 GitHub에 커밋 및 푸시합니다.', th: 'บันทึกจะเขียน labs.json ในเครื่อง; เผยแพร่จะคอมมิตและพุชไปยัง GitHub', hi: 'सहेजें स्थानीय रूप से labs.json लिखता है; प्रकाशित करें इसे GitHub पर commit और push करता है।' },
  fallbackNote: { en: 'Empty non-English fields fall back to English when learners view the lab.', zh: '非英文字段为空时，学员查看实验时将回退为英文。', ja: '英語以外が空の場合、受講者には英語が表示されます。', ko: '영어 외 필드가 비어 있으면 학습자에게 영어로 표시됩니다.', th: 'ช่องที่ไม่ใช่ภาษาอังกฤษที่ว่างเปล่าจะแสดงเป็นภาษาอังกฤษเมื่อผู้เรียนดูแล็บ', hi: 'खाली गैर-अंग्रेज़ी फ़ील्ड लैब देखते समय अंग्रेज़ी पर वापस आ जाते हैं।' },
} satisfies Record<string, LocalizedText>

export const text = (value: LocalizedText | undefined, locale: Locale): string => {
  if (!value) return ''
  const localized = value[locale]
  return localized && localized.trim() ? localized : value.en
}