import type { Locale, LocalizedText } from './types'

export const localeNames: Record<Locale, string> = {
  en: 'English',
  zh: '简体中文',
  'zh-HK': '廣東話（香港）',
  'zh-TW': '繁體中文（台灣）',
  ja: '日本語',
  ko: '한국어',
  th: 'ไทย',
  hi: 'हिन्दी',
  vi: 'Tiếng Việt',
}

export const ui = {
  program: { en: 'AI Agent Workshop by Microsoft Agent GBB', zh: 'AI Agent Workshop by Microsoft Agent GBB', ja: 'AI Agent Workshop by Microsoft Agent GBB', ko: 'AI Agent Workshop by Microsoft Agent GBB', th: 'AI Agent Workshop by Microsoft Agent GBB', hi: 'AI Agent Workshop by Microsoft Agent GBB' },
  kicker: { en: 'Hands-on learning path', zh: '动手学习路径', ja: 'ハンズオン学習パス', ko: '실습 학습 경로', th: 'เส้นทางการเรียนรู้แบบลงมือทำ', hi: 'हैंड्स-ऑन लर्निंग पाथ' },
  progress: { en: 'Overall progress', zh: '总体进度', ja: '全体の進捗', ko: '전체 진행률', th: 'ความคืบหน้าโดยรวม', hi: 'कुल प्रगति' },
  lab: { en: 'Lab', zh: '实验', ja: 'ラボ', ko: '랩', th: 'แล็บ', hi: 'लैब' },
  minutes: { en: 'min', zh: '分钟', ja: '分', ko: '분', th: 'นาที', hi: 'मिनट' },
  objectives: { en: 'Learning objectives', zh: '学习目标', ja: '学習目標', ko: '학습 목표', th: 'วัตถุประสงค์การเรียนรู้', hi: 'सीखने के उद्देश्य' },
  prerequisites: { en: 'Before you begin', zh: '开始之前', ja: '開始する前に', ko: '시작하기 전에', th: 'ก่อนเริ่มต้น', hi: 'शुरू करने से पहले' },
  outcome: { en: 'You will build', zh: '你将构建', ja: '作成するもの', ko: '구축 결과', th: 'สิ่งที่คุณจะสร้าง', hi: 'आप क्या बनाएंगे' },
  step: { en: 'Step', zh: '步骤', ja: 'ステップ', ko: '단계', th: 'ขั้นตอน', hi: 'चरण' },
  highlight: { en: 'High light', zh: '重点提示', ja: '重要ポイント', ko: '핵심 포인트', th: 'จุดสำคัญ', hi: 'मुख्य बिंदु' },
  input: { en: 'Input to use', zh: '需要输入的内容', ja: '入力内容', ko: '입력할 내용', th: 'ข้อมูลที่ต้องใช้', hi: 'उपयोग करने के लिए इनपुट' },
  copy: { en: 'Copy', zh: '复制', ja: 'コピー', ko: '복사', th: 'คัดลอก', hi: 'कॉपी' },
  copied: { en: 'Copied', zh: '已复制', ja: 'コピー済み', ko: '복사됨', th: 'คัดลอกแล้ว', hi: 'कॉपी किया गया' },
  expand: { en: 'Expand input', zh: '展开输入', ja: '入力を展開', ko: '입력 펼치기', th: 'ขยายอินพุต', hi: 'इनपुट विस्तृत करें' },
  collapse: { en: 'Collapse input', zh: '收起输入', ja: '入力を折りたたむ', ko: '입력 접기', th: 'ย่ออินพุต', hi: 'इनपुट संक्षिप्त करें' },
  complete: { en: 'Mark step complete', zh: '标记步骤完成', ja: 'ステップを完了にする', ko: '단계 완료 표시', th: 'ทำเครื่องหมายว่าเสร็จสิ้น', hi: 'चरण पूर्ण चिह्नित करें' },
  completed: { en: 'Completed', zh: '已完成', ja: '完了', ko: '완료', th: 'เสร็จสิ้น', hi: 'पूर्ण' },
  previous: { en: 'Previous', zh: '上一步', ja: '前へ', ko: '이전', th: 'ก่อนหน้า', hi: 'पिछला' },
  next: { en: 'Next', zh: '下一步', ja: '次へ', ko: '다음', th: 'ถัดไป', hi: 'अगला' },
  screenshot: { en: 'Screenshot placeholder', zh: '截图占位', ja: 'スクリーンショット予定', ko: '스크린샷 자리', th: 'ตัวอย่างภาพหน้าจอ', hi: 'स्क्रीनशॉट प्लेसहोल्डर' },
  screenshotHint: { en: 'Replace this file with the localized product screenshot.', zh: '请用对应语言的产品截图替换此文件。', ja: '該当言語の製品スクリーンショットに置き換えてください。', ko: '해당 언어의 제품 스크린샷으로 교체하세요.', th: 'แทนที่ไฟล์นี้ด้วยภาพหน้าจอผลิตภัณฑ์ในภาษาที่ต้องการ', hi: 'इस फ़ाइल को स्थानीयकृत उत्पाद स्क्रीनशॉट से बदलें।' },
  viewFullscreen: { en: 'View full screen', zh: '全屏查看', ja: '全画面で表示', ko: '전체 화면으로 보기', th: 'ดูแบบเต็มหน้าจอ', hi: 'पूर्ण स्क्रीन में देखें' },
  closeFullscreen: { en: 'Close full-screen image', zh: '关闭全屏图片', ja: '全画面画像を閉じる', ko: '전체 화면 이미지 닫기', th: 'ปิดภาพเต็มหน้าจอ', hi: 'पूर्ण-स्क्रीन छवि बंद करें' },
  previousScreenshot: { en: 'Previous screenshot', zh: '上一张截图', ja: '前のスクリーンショット', ko: '이전 스크린샷', th: 'ภาพหน้าจอก่อนหน้า', hi: 'पिछला स्क्रीनशॉट' },
  nextScreenshot: { en: 'Next screenshot', zh: '下一张截图', ja: '次のスクリーンショット', ko: '다음 스크린샷', th: 'ภาพหน้าจอถัดไป', hi: 'अगला स्क्रीनशॉट' },
  overview: { en: 'Overview', zh: '概览', ja: '概要', ko: '개요', th: 'ภาพรวม', hi: 'अवलोकन' },
  guide: { en: 'Lab guide', zh: '实验手册', ja: 'ラボ ガイド', ko: '랩 가이드', th: 'คู่มือแล็บ', hi: 'लैब गाइड' },
  contents: { en: 'In this lab', zh: '本实验内容', ja: 'このラボの内容', ko: '이 랩의 내용', th: 'ในแล็บนี้', hi: 'इस लैब में' },
  page: { en: 'Page', zh: '页面', ja: 'ページ', ko: '페이지', th: 'หน้า', hi: 'पृष्ठ' },
  theme: { en: 'Toggle color theme', zh: '切换颜色主题', ja: 'カラーテーマを切替', ko: '색상 테마 전환', th: 'สลับธีมสี', hi: 'रंग थीम टॉगल करें' },
  menu: { en: 'Open lab navigation', zh: '打开实验导航', ja: 'ラボナビを開く', ko: '랩 탐색 열기', th: 'เปิดการนำทางแล็บ', hi: 'लैब नेविगेशन खोलें' },
  close: { en: 'Close navigation', zh: '关闭导航', ja: 'ナビを閉じる', ko: '탐색 닫기', th: 'ปิดการนำทาง', hi: 'नेविगेशन बंद करें' },
  collapseSidebar: { en: 'Collapse sidebar', zh: '收起侧栏', ja: 'サイドバーを閉じる', ko: '사이드바 접기', th: 'ย่อแถบด้านข้าง', hi: 'साइडबार संक्षिप्त करें' },
  expandSidebar: { en: 'Expand sidebar', zh: '展开侧栏', ja: 'サイドバーを開く', ko: '사이드바 펼치기', th: 'ขยายแถบด้านข้าง', hi: 'साइडबार विस्तृत करें' },
  language: { en: 'Language', zh: '语言', ja: '言語', ko: '언어', th: 'ภาษา', hi: 'भाषा' },
  exportPdf: { en: 'Export this lab to PDF', zh: '将此实验导出为 PDF', ja: 'このラボを PDF にエクスポート', ko: '이 랩을 PDF로 내보내기', th: 'ส่งออกแล็บนี้เป็น PDF', hi: 'इस लैब को PDF में निर्यात करें' },
  viewLabCredentials: { en: 'View my lab credentials', zh: '查看我的实验凭据', ja: '自分のラボ資格情報を表示', ko: '내 랩 자격 증명 보기', th: 'ดูข้อมูลประจำตัวแล็บของฉัน', hi: 'मेरे लैब क्रेडेंशियल देखें' },
  labCredentialsTitle: { en: 'My lab credentials', zh: '我的实验凭据', ja: '自分のラボ資格情報', ko: '내 랩 자격 증명', th: 'ข้อมูลประจำตัวแล็บของฉัน', hi: 'मेरे लैब क्रेडेंशियल' },
  accessKey: { en: 'Access key', zh: '访问密钥', ja: 'アクセス キー', ko: '액세스 키', th: 'คีย์การเข้าถึง', hi: 'एक्सेस कुंजी' },
  labCredentialsUnavailable: { en: 'No lab credentials are assigned to this email yet.', zh: '尚未向此邮箱分配实验凭据。', ja: 'このメールにはまだラボ資格情報が割り当てられていません。', ko: '이 이메일에 아직 랩 자격 증명이 할당되지 않았습니다.', th: 'ยังไม่ได้กำหนดข้อมูลประจำตัวแล็บให้อีเมลนี้', hi: 'इस ईमेल को अभी कोई लैब क्रेडेंशियल असाइन नहीं किया गया है।' },
  labDoneTitle: { en: 'Congratulations!', zh: '恭喜！', ja: 'おめでとうございます！', ko: '축하합니다!', th: 'ยินดีด้วย!', hi: 'बधाई हो!' },
  labDoneMessage: { en: "You've completed this lab — you are awesome!", zh: '你已完成本实验——你太棒了！', ja: 'このラボを完了しました。素晴らしいです！', ko: '이 랩을 완료했어요 — 정말 멋져요!', th: 'คุณทำแล็บนี้เสร็จแล้ว — เยี่ยมมาก!', hi: 'आपने यह लैब पूरी कर ली — आप कमाल हैं!' },
  labDoneContinue: { en: 'Keep going', zh: '继续前进', ja: '次へ進む', ko: '계속하기', th: 'ไปต่อ', hi: 'आगे बढ़ें' },
  labDoneStay: { en: 'Stay here a bit', zh: '先留在这里', ja: 'もう少しここにいる', ko: '잠시 여기 머무르기', th: 'อยู่ตรงนี้ก่อน', hi: 'थोड़ी देर यहीं रहें' },
  allDoneTitle: { en: 'Brilliant!', zh: '太精彩了！', ja: '見事です！', ko: '훌륭해요!', th: 'ยอดเยี่ยม!', hi: 'शानदार!' },
  allDoneMessage: { en: "High five! You've finished every lab.", zh: '击掌！你已完成所有实验。', ja: 'ハイタッチ！すべてのラボを完了しました。', ko: '하이파이브! 모든 랩을 끝냈어요.', th: 'ไฮไฟว์! คุณทำครบทุกแล็บแล้ว', hi: 'हाई फाइव! आपने सभी लैब पूरी कर लीं।' },
  feedbackHeading: { en: 'Share your feedback', zh: '分享你的反馈', ja: 'フィードバックをお寄せください', ko: '피드백을 남겨 주세요', th: 'แบ่งปันความคิดเห็นของคุณ', hi: 'अपनी प्रतिक्रिया साझा करें' },
  feedbackIntro: { en: 'It takes less than a minute.', zh: '只需不到一分钟。', ja: '1 分もかかりません。', ko: '1분도 걸리지 않아요.', th: 'ใช้เวลาไม่ถึงหนึ่งนาที', hi: 'एक मिनट से भी कम लगता है।' },
  feedbackOverall: { en: 'Overall experience', zh: '整体体验', ja: '全体的な体験', ko: '전반적인 경험', th: 'ประสบการณ์โดยรวม', hi: 'समग्र अनुभव' },
  feedbackEffort: { en: 'Level of effort', zh: '投入程度', ja: '労力レベル', ko: '노력 수준', th: 'ระดับความพยายาม', hi: 'प्रयास का स्तर' },
  feedbackEffortHint: { en: '1 = easy · 5 = very difficult', zh: '1 = 容易 · 5 = 非常困难', ja: '1 = 簡単 · 5 = 非常に難しい', ko: '1 = 쉬움 · 5 = 매우 어려움', th: '1 = ง่าย · 5 = ยากมาก', hi: '1 = आसान · 5 = बहुत कठिन' },
  feedbackRecommend: { en: 'Would recommend to others', zh: '愿意推荐给他人', ja: '他の人に勧めたい', ko: '다른 사람에게 추천', th: 'อยากแนะนำให้ผู้อื่น', hi: 'दूसरों को सुझाना चाहेंगे' },
  feedbackComments: { en: 'Comments', zh: '评论', ja: 'コメント', ko: '의견', th: 'ความคิดเห็น', hi: 'टिप्पणियाँ' },
  feedbackCommentsHint: { en: 'What did you love? What can we improve?', zh: '你喜欢什么？我们可以改进什么？', ja: '良かった点・改善したい点は？', ko: '무엇이 좋았나요? 무엇을 개선할까요?', th: 'คุณชอบอะไร? เราควรปรับปรุงอะไร?', hi: 'आपको क्या पसंद आया? हम क्या सुधार सकते हैं?' },
  feedbackSubmit: { en: 'Submit feedback', zh: '提交反馈', ja: 'フィードバックを送信', ko: '피드백 제출', th: 'ส่งความคิดเห็น', hi: 'प्रतिक्रिया भेजें' },
  feedbackSkip: { en: 'Maybe later', zh: '以后再说', ja: '後で', ko: '나중에', th: 'ไว้ภายหลัง', hi: 'बाद में' },
  feedbackThanks: { en: 'Thank you for your feedback!', zh: '感谢你的反馈！', ja: 'フィードバックありがとうございます！', ko: '피드백 감사합니다!', th: 'ขอบคุณสำหรับความคิดเห็น!', hi: 'आपकी प्रतिक्रिया के लिए धन्यवाद!' },
  workshopBranding: { en: 'Workshop branding', zh: '研讨会品牌设置', ja: 'ワークショップのブランディング', ko: '워크숍 브랜딩', th: 'การสร้างแบรนด์เวิร์กช็อป', hi: 'वर्कशॉप ब्रांडिंग' },
  closeDialog: { en: 'Close', zh: '关闭', ja: '閉じる', ko: '닫기', th: 'ปิด', hi: 'बंद करें' },
  brandingHint: { en: 'Set a customer name or logo to co-brand this JumpStart. Save named workshops to reuse them anytime.', zh: '设置客户名称或徽标，为此 JumpStart 进行联合品牌设置。保存命名的研讨会以便随时复用。', ja: '顧客名またはロゴを設定して、この JumpStart を共同ブランディングできます。名前を付けたワークショップを保存すると、いつでも再利用できます。', ko: '고객 이름 또는 로고를 설정하여 이 JumpStart를 공동 브랜딩하세요. 이름을 지정한 워크숍을 저장해 언제든 재사용할 수 있습니다.', th: 'ตั้งชื่อหรือโลโก้ลูกค้าเพื่อร่วมสร้างแบรนด์ JumpStart นี้ บันทึกเวิร์กช็อปที่ตั้งชื่อไว้เพื่อนำกลับมาใช้ได้ทุกเมื่อ', hi: 'इस JumpStart को को-ब्रांड करने के लिए ग्राहक का नाम या लोगो सेट करें। नामित वर्कशॉप सहेजें और कभी भी दोबारा उपयोग करें।' },
  hostName: { en: 'Host name', zh: '主办方名称', ja: '主催者名', ko: '주최자 이름', th: 'ชื่อผู้จัด', hi: 'होस्ट का नाम' },
  hostLogoUrl: { en: 'Host logo URL', zh: '主办方徽标 URL', ja: '主催者ロゴの URL', ko: '주최자 로고 URL', th: 'URL โลโก้ผู้จัด', hi: 'होस्ट लोगो URL' },
  logoUrlHint: { en: 'https:// … (or upload below)', zh: 'https:// …（或在下方上传）', ja: 'https:// …（または下からアップロード）', ko: 'https:// … (또는 아래에서 업로드)', th: 'https:// … (หรืออัปโหลดด้านล่าง)', hi: 'https:// … (या नीचे अपलोड करें)' },
  uploadHostLogo: { en: 'Upload host logo', zh: '上传主办方徽标', ja: '主催者ロゴをアップロード', ko: '주최자 로고 업로드', th: 'อัปโหลดโลโก้ผู้จัด', hi: 'होस्ट लोगो अपलोड करें' },
  customerName: { en: 'Customer name', zh: '客户名称', ja: '顧客名', ko: '고객 이름', th: 'ชื่อลูกค้า', hi: 'ग्राहक का नाम' },
  customerNameHint: { en: 'e.g. Contoso', zh: '例如：Contoso', ja: '例: Contoso', ko: '예: Contoso', th: 'เช่น Contoso', hi: 'उदा. Contoso' },
  customerLogoUrl: { en: 'Customer logo URL', zh: '客户徽标 URL', ja: '顧客ロゴの URL', ko: '고객 로고 URL', th: 'URL โลโก้ลูกค้า', hi: 'ग्राहक लोगो URL' },
  uploadCustomerLogo: { en: 'Upload customer logo', zh: '上传客户徽标', ja: '顧客ロゴをアップロード', ko: '고객 로고 업로드', th: 'อัปโหลดโลโก้ลูกค้า', hi: 'ग्राहक लोगो अपलोड करें' },
  removeLogo: { en: 'Remove', zh: '移除', ja: '削除', ko: '제거', th: 'ลบ', hi: 'हटाएं' },
  reset: { en: 'Reset', zh: '重置', ja: 'リセット', ko: '재설정', th: 'รีเซ็ต', hi: 'रीसेट' },
  saveToHistory: { en: 'Save to history', zh: '保存到历史记录', ja: '履歴に保存', ko: '기록에 저장', th: 'บันทึกลงประวัติ', hi: 'इतिहास में सहेजें' },
  apply: { en: 'Apply', zh: '应用', ja: '適用', ko: '적용', th: 'ใช้งาน', hi: 'लागू करें' },
  applying: { en: 'Applying…', zh: '正在应用…', ja: '適用中…', ko: '적용 중…', th: 'กำลังใช้งาน…', hi: 'लागू किया जा रहा है…' },
  brandingPublished: { en: 'Applied and published to branding.json. Commit and push so everyone sees it.', zh: '已应用并发布到 branding.json。请提交并推送，以便所有人都能看到。', ja: 'branding.json に適用・公開しました。全員に表示するにはコミットしてプッシュしてください。', ko: 'branding.json에 적용 및 게시했습니다. 모두가 볼 수 있도록 커밋하고 푸시하세요.', th: 'ใช้งานและเผยแพร่ไปยัง branding.json แล้ว คอมมิตและพุชเพื่อให้ทุกคนเห็น', hi: 'branding.json पर लागू और प्रकाशित किया गया। सभी को दिखाने के लिए commit और push करें।' },
  brandingSaveFailed: { en: 'Could not save branding.json. Your changes are still in this form; select Apply to try again.', zh: '无法保存 branding.json。您的更改仍保留在此表单中；请选择“应用”重试。', ja: 'branding.json を保存できませんでした。変更はこのフォームに残っています。「適用」を選択して再試行してください。', ko: 'branding.json을 저장할 수 없습니다. 변경 사항은 이 양식에 남아 있습니다. 적용을 선택하여 다시 시도하세요.', th: 'ไม่สามารถบันทึก branding.json ได้ การเปลี่ยนแปลงยังอยู่ในแบบฟอร์มนี้ เลือกใช้งานเพื่อลองอีกครั้ง', hi: 'branding.json सहेजा नहीं जा सका। आपके बदलाव अभी भी इस फ़ॉर्म में हैं; फिर कोशिश करने के लिए लागू करें चुनें।' },
  workshopHistory: { en: 'Workshop history', zh: '研讨会历史记录', ja: 'ワークショップ履歴', ko: '워크숍 기록', th: 'ประวัติเวิร์กช็อป', hi: 'वर्कशॉप इतिहास' },
  searchWorkshops: { en: 'Quick search saved workshops…', zh: '快速搜索已保存的研讨会…', ja: '保存したワークショップをすばやく検索…', ko: '저장된 워크숍 빠른 검색…', th: 'ค้นหาเวิร์กช็อปที่บันทึกไว้อย่างรวดเร็ว…', hi: 'सहेजे गए वर्कशॉप त्वरित खोजें…' },
  noSavedWorkshops: { en: 'No saved workshops yet. Configure branding above, then select “Save to history.”', zh: '尚无已保存的研讨会。请先配置上方的品牌设置，然后选择“保存到历史记录”。', ja: '保存されたワークショップはまだありません。上でブランディングを設定し、「履歴に保存」を選択してください。', ko: '저장된 워크숍이 아직 없습니다. 위에서 브랜딩을 구성한 다음 “기록에 저장”을 선택하세요.', th: 'ยังไม่มีเวิร์กช็อปที่บันทึกไว้ กำหนดค่าแบรนด์ด้านบน แล้วเลือก “บันทึกลงประวัติ”', hi: 'अभी तक कोई सहेजा हुआ वर्कशॉप नहीं। ऊपर ब्रांडिंग कॉन्फ़िगर करें, फिर “इतिहास में सहेजें” चुनें।' },
  noMatchingWorkshops: { en: 'No workshops match your search.', zh: '没有与搜索匹配的研讨会。', ja: '検索に一致するワークショップはありません。', ko: '검색과 일치하는 워크숍이 없습니다.', th: 'ไม่มีเวิร์กช็อปที่ตรงกับการค้นหา', hi: 'आपकी खोज से कोई वर्कशॉप मेल नहीं खाता।' },
  loadWorkshop: { en: 'Load into the form', zh: '加载到表单', ja: 'フォームに読み込む', ko: '양식으로 불러오기', th: 'โหลดลงในฟอร์ม', hi: 'फ़ॉर्म में लोड करें' },
  deleteWorkshop: { en: 'Delete {name}', zh: '删除 {name}', ja: '{name} を削除', ko: '{name} 삭제', th: 'ลบ {name}', hi: '{name} हटाएं' },
  savedWorkshop: { en: 'Saved “{name}”', zh: '已保存“{name}”', ja: '「{name}」を保存しました', ko: '“{name}” 저장됨', th: 'บันทึก “{name}” แล้ว', hi: '“{name}” सहेजा गया' },
  updatedWorkshop: { en: 'Updated “{name}”', zh: '已更新“{name}”', ja: '「{name}」を更新しました', ko: '“{name}” 업데이트됨', th: 'อัปเดต “{name}” แล้ว', hi: '“{name}” अपडेट किया गया' },
  loadedWorkshop: { en: 'Loaded “{name}” — select Apply to use it', zh: '已加载“{name}”——选择“应用”以使用它', ja: '「{name}」を読み込みました。使用するには「適用」を選択してください', ko: '“{name}”을 불러왔습니다. 사용하려면 적용을 선택하세요', th: 'โหลด “{name}” แล้ว — เลือกใช้งานเพื่อใช้', hi: '“{name}” लोड किया गया — उपयोग के लिए Apply चुनें' },
  maker: { en: 'Maker mode', zh: '创作者模式', ja: 'メーカー モード', ko: '메이커 모드', th: 'โหมดผู้สร้าง', hi: 'मेकर मोड' },
  makerUnlock: { en: 'Enter maker password', zh: '输入创作者密码', ja: 'メーカー パスワードを入力', ko: '메이커 암호 입력', th: 'ป้อนรหัสผ่านผู้สร้าง', hi: 'मेकर पासवर्ड दर्ज करें' },
  makerWrong: { en: 'Incorrect password', zh: '密码错误', ja: 'パスワードが違います', ko: '암호가 올바르지 않습니다', th: 'รหัสผ่านไม่ถูกต้อง', hi: 'गलत पासवर्ड' },
  reauthHint: { en: 'Your maker session expired. Enter the password to keep editing and save.', zh: '创作者会话已过期。请输入密码以继续编辑并保存。', ja: 'メーカー セッションの有効期限が切れました。編集と保存を続けるにはパスワードを入力してください。', ko: '메이커 세션이 만료되었습니다. 계속 편집하고 저장하려면 암호를 입력하세요.', th: 'เซสชันผู้สร้างหมดอายุ ป้อนรหัสผ่านเพื่อแก้ไขและบันทึกต่อ', hi: 'आपका मेकर सत्र समाप्त हो गया। संपादन और सहेजना जारी रखने के लिए पासवर्ड दर्ज करें।' },
  unlock: { en: 'Unlock', zh: '解锁', ja: 'ロック解除', ko: '잠금 해제', th: 'ปลดล็อก', hi: 'अनलॉक' },
  exitMaker: { en: 'Exit maker mode', zh: '退出创作者模式', ja: 'メーカー モードを終了', ko: '메이커 모드 종료', th: 'ออกจากโหมดผู้สร้าง', hi: 'मेकर मोड से बाहर निकलें' },
  editContent: { en: 'Edit content', zh: '编辑内容', ja: 'コンテンツを編集', ko: '콘텐츠 편집', th: 'แก้ไขเนื้อหา', hi: 'सामग्री संपादित करें' },
  editingLanguage: { en: 'Editing language', zh: '编辑语言', ja: '編集言語', ko: '편집 언어', th: 'ภาษาที่แก้ไข', hi: 'संपादन भाषा' },
  copyEnglish: { en: 'Copy from English', zh: '从英文复制', ja: '英語からコピー', ko: '영어에서 복사', th: 'คัดลอกจากภาษาอังกฤษ', hi: 'अंग्रेज़ी से कॉपी करें' },
  save: { en: 'Save', zh: '保存', ja: '保存', ko: '저장', th: 'บันทึก', hi: 'सहेजें' },
  saving: { en: 'Saving…', zh: '正在保存…', ja: '保存中…', ko: '저장 중…', th: 'กำลังบันทึก…', hi: 'सहेजा जा रहा है…' },
  saved: { en: 'Saved', zh: '已保存', ja: '保存しました', ko: '저장됨', th: 'บันทึกแล้ว', hi: 'सहेजा गया' },
  publish: { en: 'Publish to GitHub', zh: '发布到 GitHub', ja: 'GitHub に公開', ko: 'GitHub에 게시', th: 'เผยแพร่ไปยัง GitHub', hi: 'GitHub पर प्रकाशित करें' },
  publishing: { en: 'Publishing…', zh: '正在发布…', ja: '公開中…', ko: '게시 중…', th: 'กำลังเผยแพร่…', hi: 'प्रकाशित किया जा रहा है…' },
  published: { en: 'Published', zh: '已发布', ja: '公開しました', ko: '게시됨', th: 'เผยแพร่แล้ว', hi: 'प्रकाशित' },
  discard: { en: 'Discard changes', zh: '放弃更改', ja: '変更を破棄', ko: '변경 취소', th: 'ยกเลิกการเปลี่ยนแปลง', hi: 'परिवर्तन खारिज करें' },
  addLab: { en: 'Add lab', zh: '添加实验', ja: 'ラボを追加', ko: '랩 추가', th: 'เพิ่มแล็บ', hi: 'लैब जोड़ें' },
  addStep: { en: 'Add step', zh: '添加步骤', ja: 'ステップを追加', ko: '단계 추가', th: 'เพิ่มขั้นตอน', hi: 'चरण जोड़ें' },
  addPage: { en: 'Add page', zh: '添加页面', ja: 'ページを追加', ko: '페이지 추가', th: 'เพิ่มหน้า', hi: 'पृष्ठ जोड़ें' },
  addParagraph: { en: 'Add paragraph', zh: '添加段落', ja: '段落を追加', ko: '단락 추가', th: 'เพิ่มย่อหน้า', hi: 'अनुच्छेद जोड़ें' },
  addObjective: { en: 'Add objective', zh: '添加目标', ja: '目標を追加', ko: '목표 추가', th: 'เพิ่มวัตถุประสงค์', hi: 'उद्देश्य जोड़ें' },
  addPrerequisite: { en: 'Add prerequisite', zh: '添加前提', ja: '前提条件を追加', ko: '전제 조건 추가', th: 'เพิ่มข้อกำหนดเบื้องต้น', hi: 'पूर्वापेक्षा जोड़ें' },
  addImage: { en: 'Add screenshot key', zh: '添加截图键', ja: 'スクショ キーを追加', ko: '스크린샷 키 추가', th: 'เพิ่มคีย์ภาพหน้าจอ', hi: 'स्क्रीनशॉट कुंजी जोड़ें' },
  remove: { en: 'Remove', zh: '删除', ja: '削除', ko: '삭제', th: 'ลบ', hi: 'हटाएं' },
  moveUp: { en: 'Move up', zh: '上移', ja: '上へ', ko: '위로', th: 'เลื่อนขึ้น', hi: 'ऊपर ले जाएं' },
  moveDown: { en: 'Move down', zh: '下移', ja: '下へ', ko: '아래로', th: 'เลื่อนลง', hi: 'नीचे ले जाएं' },
  labTitle: { en: 'Lab title', zh: '实验标题', ja: 'ラボ タイトル', ko: '랩 제목', th: 'ชื่อแล็บ', hi: 'लैब शीर्षक' },
  labSummary: { en: 'Summary', zh: '摘要', ja: '概要', ko: '요약', th: 'สรุป', hi: 'सारांश' },
  labOutcome: { en: 'Outcome', zh: '成果', ja: '成果', ko: '결과', th: 'ผลลัพธ์', hi: 'परिणाम' },
  labIcon: { en: 'Icon', zh: '图标', ja: 'アイコン', ko: '아이콘', th: 'ไอคอน', hi: 'आइकन' },
  labDuration: { en: 'Duration (min)', zh: '时长（分钟）', ja: '所要時間（分）', ko: '소요 시간(분)', th: 'ระยะเวลา (นาที)', hi: 'अवधि (मिनट)' },
  labVisibility: { en: 'Visibility', zh: '可见性', ja: '公開設定', ko: '공개 설정', th: 'การมองเห็น', hi: 'दृश्यता' },
  isPublic: { en: 'Public', zh: '公开', ja: '公開', ko: '공개', th: 'สาธารณะ', hi: 'सार्वजनिक' },
  isPrivate: { en: 'Private (build only)', zh: '私有（仅构建）', ja: '非公開（作成のみ）', ko: '비공개(빌드 전용)', th: 'ส่วนตัว (สร้างเท่านั้น)', hi: 'निजी (केवल बिल्ड)' },
  publicLab: { en: 'Public — visible to workshop users when published, and counts toward progress.', zh: '公开——发布后研讨会用户可见，并计入进度。', ja: '公開 — 公開後にワークショップ利用者に表示され、進捗にカウントされます。', ko: '공개 — 게시 후 워크숍 사용자에게 표시되며 진행률에 포함됩니다.', th: 'สาธารณะ — ผู้ใช้เวิร์กช็อปเห็นเมื่อเผยแพร่ และนับรวมในความคืบหน้า', hi: 'सार्वजनिक — प्रकाशित होने पर वर्कशॉप उपयोगकर्ताओं को दिखता है और प्रगति में गिना जाता है।' },
  privateLab: { en: 'Private — build-only draft. Hidden from the published workshop and excluded from progress.', zh: '私有——仅用于构建的草稿。不会出现在已发布的研讨会中，也不计入进度。', ja: '非公開 — 作成専用の下書き。公開されたワークショップには表示されず、進捗にも含まれません。', ko: '비공개 — 빌드 전용 초안입니다. 게시된 워크숍에서 숨겨지고 진행률에서 제외됩니다.', th: 'ส่วนตัว — ฉบับร่างสำหรับสร้างเท่านั้น ซ่อนจากเวิร์กช็อปที่เผยแพร่และไม่นับรวมในความคืบหน้า', hi: 'निजी — केवल-बिल्ड ड्राफ़्ट। प्रकाशित वर्कशॉप से छिपा और प्रगति से बाहर।' },
  privateBadge: { en: 'Private', zh: '私有', ja: '非公開', ko: '비공개', th: 'ส่วนตัว', hi: 'निजी' },
  cloneStep: { en: 'Clone step', zh: '克隆步骤', ja: 'ステップを複製', ko: '단계 복제', th: 'โคลนขั้นตอน', hi: 'चरण क्लोन करें' },
  stepVisibility: { en: 'Step visibility', zh: '步骤可见性', ja: 'ステップの公開設定', ko: '단계 공개 설정', th: 'การมองเห็นขั้นตอน', hi: 'चरण दृश्यता' },
  stepVisible: { en: 'Visible', zh: '可见', ja: '表示', ko: '표시', th: 'มองเห็น', hi: 'दृश्य' },
  stepHidden: { en: 'Hidden', zh: '隐藏', ja: '非表示', ko: '숨김', th: 'ซ่อน', hi: 'छिपा' },
  stepVisibleHint: { en: 'Visible — shown to lab users and counted toward progress.', zh: '可见——向实验用户显示，并计入进度。', ja: '表示 — ラボ利用者に表示され、進捗にカウントされます。', ko: '표시 — 랩 사용자에게 보이며 진행률에 포함됩니다.', th: 'มองเห็น — แสดงต่อผู้ใช้แล็บและนับรวมในความคืบหน้า', hi: 'दृश्य — लैब उपयोगकर्ताओं को दिखता है और प्रगति में गिना जाता है।' },
  stepHiddenHint: { en: 'Hidden — removed from the lab reader, navigation, and progress for lab users.', zh: '隐藏——不会出现在实验阅读视图、导航和用户进度中。', ja: '非表示 — ラボの閲覧画面・ナビゲーション・進捗から除外されます。', ko: '숨김 — 랩 리더, 탐색, 진행률에서 제외됩니다.', th: 'ซ่อน — ถูกนำออกจากมุมมองอ่านแล็บ การนำทาง และความคืบหน้าของผู้ใช้', hi: 'छिपा — लैब रीडर, नेविगेशन और उपयोगकर्ता प्रगति से हटा दिया गया।' },
  stepTitle: { en: 'Step title (Markdown)', zh: '步骤标题（Markdown）', ja: 'ステップ タイトル（Markdown）', ko: '단계 제목(Markdown)', th: 'ชื่อขั้นตอน (Markdown)', hi: 'चरण शीर्षक (Markdown)' },
  pageTitle: { en: 'Page title (Markdown, optional)', zh: '页面标题（Markdown，可选）', ja: 'ページ タイトル（Markdown・任意）', ko: '페이지 제목(Markdown, 선택)', th: 'ชื่อหน้า (Markdown, ไม่บังคับ)', hi: 'पृष्ठ शीर्षक (Markdown, वैकल्पिक)' },
  fieldHighlight: { en: 'Highlight Markdown (optional)', zh: '重点提示 Markdown（可选）', ja: '重要ポイント Markdown（任意）', ko: '핵심 포인트 Markdown(선택)', th: 'จุดสำคัญ Markdown (ไม่บังคับ)', hi: 'हाइलाइट Markdown (वैकल्पिक)' },
  fieldPrompt: { en: 'Input / prompt content (same for all languages)', zh: '输入/提示内容（所有语言相同）', ja: '入力/プロンプト内容（全言語共通）', ko: '입력/프롬프트 내용(모든 언어 공통)', th: 'เนื้อหาอินพุต/พรอมป์ต์ (เหมือนกันทุกภาษา)', hi: 'इनपुट / प्रॉम्प्ट सामग्री (सभी भाषाओं के लिए समान)' },
  fieldPromptTitle: { en: 'Input title (e.g. Agent instruction, Skill)', zh: '输入标题（例如：Agent 指令、Skill）', ja: '入力タイトル（例：Agent 指示、Skill）', ko: '입력 제목(예: Agent 지침, Skill)', th: 'ชื่ออินพุต (เช่น Agent instruction, Skill)', hi: 'इनपुट शीर्षक (उदा. Agent instruction, Skill)' },
  addPrompt: { en: 'Add input / prompt', zh: '添加输入/提示', ja: '入力/プロンプトを追加', ko: '입력/프롬프트 추가', th: 'เพิ่มอินพุต/พรอมป์ต์', hi: 'इनपुट / प्रॉम्प्ट जोड़ें' },
  promptDefaultTitle: { en: 'Instructions / Input', zh: '说明/输入', ja: '指示/入力', ko: '지침/입력', th: 'คำแนะนำ/อินพุต', hi: 'निर्देश / इनपुट' },
  publishHint: { en: 'Save writes labs.json locally; Publish commits and pushes it to GitHub.', zh: '保存会写入本地 labs.json；发布会提交并推送到 GitHub。', ja: '保存はローカルの labs.json に書き込み、公開は GitHub にコミット & プッシュします。', ko: '저장은 로컬 labs.json에 기록하고, 게시는 GitHub에 커밋 및 푸시합니다.', th: 'บันทึกจะเขียน labs.json ในเครื่อง; เผยแพร่จะคอมมิตและพุชไปยัง GitHub', hi: 'सहेजें स्थानीय रूप से labs.json लिखता है; प्रकाशित करें इसे GitHub पर commit और push करता है।' },
  fallbackNote: { en: 'Empty non-English fields fall back to English when learners view the lab.', zh: '非英文字段为空时，学员查看实验时将回退为英文。', ja: '英語以外が空の場合、受講者には英語が表示されます。', ko: '영어 외 필드가 비어 있으면 학습자에게 영어로 표시됩니다.', th: 'ช่องที่ไม่ใช่ภาษาอังกฤษที่ว่างเปล่าจะแสดงเป็นภาษาอังกฤษเมื่อผู้เรียนดูแล็บ', hi: 'खाली गैर-अंग्रेज़ी फ़ील्ड लैब देखते समय अंग्रेज़ी पर वापस आ जाते हैं।' },
  preparedByField: { en: 'Prepared by', zh: '准备者', ja: '作成者', ko: '작성자', th: 'จัดทำโดย', hi: 'द्वारा तैयार' },
  preparedDateField: { en: 'Prepared date', zh: '编写日期', ja: '作成日', ko: '작성일', th: 'วันที่จัดทำ', hi: 'तैयारी की तारीख' },
  workshopAccessWindow: { en: 'Workshop access window', zh: '研讨会访问时段', ja: 'ワークショップのアクセス期間', ko: '워크숍 액세스 기간', th: 'ช่วงเวลาเข้าเวิร์กช็อป', hi: 'वर्कशॉप एक्सेस अवधि' },
  workshopAccessWindowHint: { en: 'Optional. Set both dates to allow entry from 00:00 on the start date through 23:59:59 on the end date.', zh: '可选。同时设置开始和结束日期后，可在开始日期 00:00 至结束日期 23:59:59 之间进入。', ja: '任意。開始日と終了日の両方を設定すると、開始日の 00:00 から終了日の 23:59:59 まで入場できます。', ko: '선택 사항. 시작일과 종료일을 모두 설정하면 시작일 00:00부터 종료일 23:59:59까지 입장할 수 있습니다.', th: 'ไม่บังคับ กำหนดวันที่ทั้งสองเพื่อให้เข้าได้ตั้งแต่ 00:00 ของวันที่เริ่มต้นถึง 23:59:59 ของวันที่สิ้นสุด', hi: 'वैकल्पिक। आरंभ तारीख को 00:00 बजे से समाप्ति तारीख को 23:59:59 बजे तक प्रवेश देने के लिए दोनों तारीखें सेट करें।' },
  workshopStartDate: { en: 'Start date', zh: '开始日期', ja: '開始日', ko: '시작일', th: 'วันที่เริ่มต้น', hi: 'आरंभ तारीख' },
  workshopEndDate: { en: 'End date', zh: '结束日期', ja: '終了日', ko: '종료일', th: 'วันที่สิ้นสุด', hi: 'समाप्ति तारीख' },
  workshopWindowInvalid: { en: 'Set both dates and make the end date the same as or later than the start date.', zh: '请同时设置开始与结束日期，并确保结束日期不早于开始日期。', ja: '開始日と終了日の両方を設定し、終了日を開始日以降にしてください。', ko: '두 날짜를 모두 설정하고 종료일을 시작일과 같거나 늦게 지정하세요.', th: 'กำหนดวันที่ทั้งสองและให้วันที่สิ้นสุดเป็นวันเดียวกับหรือหลังวันที่เริ่มต้น', hi: 'दोनों तारीखें सेट करें और समाप्ति तारीख को आरंभ तारीख के समान या उसके बाद रखें।' },
  contactsField: { en: 'Need help? Contacts', zh: '需要帮助？联系人', ja: 'お困りですか？ 連絡先', ko: '도움이 필요하신가요? 연락처', th: 'ต้องการความช่วยเหลือ? ผู้ติดต่อ', hi: 'मदद चाहिए? संपर्क' },
  contactNameHint: { en: 'Name (e.g. Jane Doe)', zh: '姓名（例如：张三）', ja: '名前（例：山田太郎）', ko: '이름(예: 홍길동)', th: 'ชื่อ (เช่น สมชาย)', hi: 'नाम (उदा. जेन डो)' },
  contactEmailHint: { en: 'email@microsoft.com', zh: 'email@microsoft.com', ja: 'email@microsoft.com', ko: 'email@microsoft.com', th: 'email@microsoft.com', hi: 'email@microsoft.com' },
  addContact: { en: 'Add contact', zh: '添加联系人', ja: '連絡先を追加', ko: '연락처 추가', th: 'เพิ่มผู้ติดต่อ', hi: 'संपर्क जोड़ें' },
  removeContact: { en: 'Remove contact', zh: '删除联系人', ja: '連絡先を削除', ko: '연락처 삭제', th: 'ลบผู้ติดต่อ', hi: 'संपर्क हटाएं' },
  attendeesField: { en: 'Attendee email list', zh: '参会者邮箱列表', ja: '参加者メールリスト', ko: '참석자 이메일 목록', th: 'รายชื่ออีเมลผู้เข้าร่วม', hi: 'उपस्थित ईमेल सूची' },
  attendeesHint: { en: 'Optional. When set, participants must verify their email on the welcome page before entering the labs. Add one at a time, or paste a comma / space / tab-separated list.', zh: '可选。设置后，参会者必须在欢迎页面验证邮箱才能进入实验。可逐个添加，或粘贴以逗号／空格／制表符分隔的列表。', ja: '任意。設定すると、参加者はラボに入る前にウェルカムページでメールを確認する必要があります。1件ずつ追加するか、カンマ・スペース・タブ区切りのリストを貼り付けます。', ko: '선택 사항. 설정하면 참가자는 랩에 들어가기 전에 환영 페이지에서 이메일을 확인해야 합니다. 하나씩 추가하거나 쉼표/공백/탭으로 구분된 목록을 붙여넣으세요.', th: 'ไม่บังคับ เมื่อกำหนดแล้ว ผู้เข้าร่วมต้องยืนยันอีเมลในหน้าต้อนรับก่อนเข้าแล็บ เพิ่มทีละรายการ หรือวางรายการที่คั่นด้วยจุลภาค / เว้นวรรค / แท็บ', hi: 'वैकल्पिक। सेट होने पर, प्रतिभागियों को लैब में प्रवेश करने से पहले स्वागत पृष्ठ पर अपना ईमेल सत्यापित करना होगा। एक-एक करके जोड़ें, या अल्पविराम / स्थान / टैब से अलग की गई सूची पेस्ट करें।' },
  addAttendee: { en: 'Add', zh: '添加', ja: '追加', ko: '추가', th: 'เพิ่ม', hi: 'जोड़ें' },
  attendeeAddHint: { en: 'name@company.com', zh: 'name@company.com', ja: 'name@company.com', ko: 'name@company.com', th: 'name@company.com', hi: 'name@company.com' },
  attendeePasteHint: { en: 'Paste emails separated by commas, spaces, tabs, or new lines…', zh: '粘贴以逗号、空格、制表符或换行分隔的邮箱…', ja: 'カンマ・スペース・タブ・改行で区切ったメールを貼り付け…', ko: '쉼표, 공백, 탭 또는 줄바꿈으로 구분된 이메일 붙여넣기…', th: 'วางอีเมลที่คั่นด้วยจุลภาค เว้นวรรค แท็บ หรือขึ้นบรรทัดใหม่…', hi: 'अल्पविराम, स्थान, टैब या नई पंक्तियों से अलग किए गए ईमेल पेस्ट करें…' },
  addPastedList: { en: 'Add pasted list', zh: '添加粘贴的列表', ja: '貼り付けたリストを追加', ko: '붙여넣은 목록 추가', th: 'เพิ่มรายการที่วาง', hi: 'पेस्ट की गई सूची जोड़ें' },
  clearAll: { en: 'Clear all', zh: '全部清除', ja: 'すべてクリア', ko: '모두 지우기', th: 'ล้างทั้งหมด', hi: 'सभी साफ़ करें' },
  removeAttendee: { en: 'Remove attendee', zh: '删除参会者', ja: '参加者を削除', ko: '참석자 제거', th: 'ลบผู้เข้าร่วม', hi: 'उपस्थित हटाएं' },
  attendeesAdded: { en: '{n} added', zh: '已添加 {n} 个', ja: '{n} 件追加', ko: '{n}개 추가됨', th: 'เพิ่ม {n} รายการ', hi: '{n} जोड़े गए' },
  attendeesNoneAdded: { en: 'No valid email addresses found', zh: '未找到有效的邮箱地址', ja: '有効なメールアドレスが見つかりません', ko: '유효한 이메일 주소가 없습니다', th: 'ไม่พบที่อยู่อีเมลที่ถูกต้อง', hi: 'कोई मान्य ईमेल पता नहीं मिला' },
  labUsersField: { en: 'Lab users and access codes', zh: '实验用户和访问代码', ja: 'ラボ ユーザーとアクセス コード', ko: '랩 사용자 및 액세스 코드', th: 'ผู้ใช้แล็บและรหัสเข้าถึง', hi: 'लैब उपयोगकर्ता और एक्सेस कोड' },
  labUsersHint: { en: 'Paste two columns copied from Excel. These credentials are stored with this branding configuration and assigned to attendee emails in a repeating sequence.', zh: '粘贴从 Excel 复制的两列。这些凭据将随此品牌配置一起保存，并按循环顺序分配给参会者邮箱。', ja: 'Excel からコピーした 2 列を貼り付けます。資格情報はこのブランド設定と共に保存され、参加者メールに繰り返し順番で割り当てられます。', ko: 'Excel에서 복사한 두 열을 붙여넣으세요. 이 자격 증명은 브랜딩 구성과 함께 저장되며 참석자 이메일에 반복 순서로 할당됩니다.', th: 'วางสองคอลัมน์ที่คัดลอกจาก Excel ข้อมูลประจำตัวจะถูกบันทึกกับการกำหนดค่าแบรนด์นี้และจัดสรรให้อีเมลผู้เข้าร่วมแบบวนซ้ำ', hi: 'Excel से कॉपी किए गए दो कॉलम पेस्ट करें। ये क्रेडेंशियल इस ब्रांडिंग कॉन्फ़िगरेशन के साथ सहेजे जाते हैं और उपस्थित लोगों के ईमेल को दोहराते क्रम में दिए जाते हैं।' },
  labUsersPasteHint: { en: 'Paste Excel columns: lab user name    access code', zh: '粘贴 Excel 列：实验用户名    访问代码', ja: 'Excel の列を貼り付け: ラボ ユーザー名    アクセス コード', ko: 'Excel 열 붙여넣기: 랩 사용자 이름    액세스 코드', th: 'วางคอลัมน์ Excel: ชื่อผู้ใช้แล็บ    รหัสเข้าถึง', hi: 'Excel कॉलम पेस्ट करें: लैब उपयोगकर्ता नाम    एक्सेस कोड' },
  labUserNameColumn: { en: 'Lab user name', zh: '实验用户名', ja: 'ラボ ユーザー名', ko: '랩 사용자 이름', th: 'ชื่อผู้ใช้แล็บ', hi: 'लैब उपयोगकर्ता नाम' },
  accessCodeColumn: { en: 'Access code', zh: '访问代码', ja: 'アクセス コード', ko: '액세스 코드', th: 'รหัสเข้าถึง', hi: 'एक्सेस कोड' },
  attendeeEmailColumn: { en: 'Attendee email', zh: '参会者邮箱', ja: '参加者メール', ko: '참석자 이메일', th: 'อีเมลผู้เข้าร่วม', hi: 'उपस्थित व्यक्ति का ईमेल' },
  addLabUser: { en: 'Add row', zh: '添加行', ja: '行を追加', ko: '행 추가', th: 'เพิ่มแถว', hi: 'पंक्ति जोड़ें' },
  labUsersImported: { en: 'Imported {n} lab users', zh: '已导入 {n} 个实验用户', ja: '{n} 件のラボ ユーザーをインポートしました', ko: '랩 사용자 {n}명을 가져왔습니다', th: 'นำเข้าผู้ใช้แล็บ {n} รายการแล้ว', hi: '{n} लैब उपयोगकर्ता आयात किए गए' },
  labUsersNoneAdded: { en: 'No complete two-column rows found', zh: '未找到完整的两列数据行', ja: '完全な 2 列の行が見つかりません', ko: '완전한 두 열 행을 찾을 수 없습니다', th: 'ไม่พบแถวสองคอลัมน์ที่สมบูรณ์', hi: 'कोई पूरी दो-कॉलम पंक्ति नहीं मिली' },
  labUsersIncomplete: { en: 'Each lab user row needs both a user name and an access code.', zh: '每个实验用户行都必须包含用户名和访问代码。', ja: '各ラボ ユーザー行には、ユーザー名とアクセス コードの両方が必要です。', ko: '각 랩 사용자 행에는 사용자 이름과 액세스 코드가 모두 필요합니다.', th: 'แต่ละแถวของผู้ใช้แล็บต้องมีทั้งชื่อผู้ใช้และรหัสเข้าถึง', hi: 'हर लैब उपयोगकर्ता पंक्ति में उपयोगकर्ता नाम और एक्सेस कोड दोनों होने चाहिए।' },
  generateUserMapping: { en: 'Generate User Mapping', zh: '生成用户映射', ja: 'ユーザー マッピングを生成', ko: '사용자 매핑 생성', th: 'สร้างการแมปผู้ใช้', hi: 'उपयोगकर्ता मैपिंग जनरेट करें' },
  generatingUserMapping: { en: 'Generating…', zh: '正在生成…', ja: '生成中…', ko: '생성 중…', th: 'กำลังสร้าง…', hi: 'जनरेट हो रहा है…' },
  userMappingGenerated: { en: 'Downloaded mappings for {n} attendees', zh: '已下载 {n} 位参会者的映射', ja: '{n} 名分のマッピングをダウンロードしました', ko: '참석자 {n}명의 매핑을 다운로드했습니다', th: 'ดาวน์โหลดการแมปสำหรับผู้เข้าร่วม {n} รายการแล้ว', hi: '{n} उपस्थित लोगों की मैपिंग डाउनलोड की गई' },
  userMappingFailed: { en: 'Could not generate the user mapping workbook. Please try again.', zh: '无法生成用户映射工作簿。请重试。', ja: 'ユーザー マッピング ブックを生成できませんでした。もう一度お試しください。', ko: '사용자 매핑 통합 문서를 생성할 수 없습니다. 다시 시도하세요.', th: 'ไม่สามารถสร้างเวิร์กบุ๊กการแมปผู้ใช้ได้ โปรดลองอีกครั้ง', hi: 'उपयोगकर्ता मैपिंग वर्कबुक जनरेट नहीं की जा सकी। कृपया फिर कोशिश करें।' },
  attendeeGateTitle: { en: 'Verify your email', zh: '验证您的邮箱', ja: 'メールを確認', ko: '이메일 확인', th: 'ยืนยันอีเมลของคุณ', hi: 'अपना ईमेल सत्यापित करें' },
  attendeeGateIntro: { en: 'This workshop is open to registered attendees. Enter your email to continue.', zh: '本研讨会仅面向已登记的参会者。请输入您的邮箱以继续。', ja: 'このワークショップは登録済みの参加者が対象です。続行するにはメールを入力してください。', ko: '이 워크숍은 등록된 참석자를 위한 것입니다. 계속하려면 이메일을 입력하세요.', th: 'เวิร์กช็อปนี้เปิดสำหรับผู้เข้าร่วมที่ลงทะเบียนแล้ว กรอกอีเมลของคุณเพื่อดำเนินการต่อ', hi: 'यह वर्कशॉप पंजीकृत उपस्थित लोगों के लिए है। जारी रखने के लिए अपना ईमेल दर्ज करें।' },
  accessWelcomePrompt: { en: 'Enter your work email to continue to the workshop welcome page.', zh: '请输入您的工作邮箱，以继续前往研讨会欢迎页面。', ja: 'ワークショップのウェルカム ページに進むには、仕事用メールを入力してください。', ko: '워크숍 환영 페이지로 계속하려면 업무 이메일을 입력하세요.', th: 'กรอกอีเมลที่ทำงานเพื่อไปยังหน้าต้อนรับของเวิร์กช็อป', hi: 'वर्कशॉप स्वागत पृष्ठ पर जाने के लिए अपना कार्य ईमेल दर्ज करें।' },
  attendeeGateLabel: { en: 'Work email', zh: '工作邮箱', ja: '仕事用メール', ko: '업무 이메일', th: 'อีเมลที่ทำงาน', hi: 'कार्य ईमेल' },
  attendeeGateVerify: { en: 'Verify & enter', zh: '验证并进入', ja: '確認して開始', ko: '확인 후 시작', th: 'ยืนยันและเข้า', hi: 'सत्यापित करें और प्रवेश करें' },
  attendeeGateContinue: { en: 'Verify & continue', zh: '验证并继续', ja: '確認して続行', ko: '확인 후 계속', th: 'ยืนยันและดำเนินการต่อ', hi: 'सत्यापित करें और जारी रखें' },
  attendeeGateInvalid: { en: 'Please enter a valid email address.', zh: '请输入有效的邮箱地址。', ja: '有効なメールアドレスを入力してください。', ko: '유효한 이메일 주소를 입력하세요.', th: 'กรุณากรอกที่อยู่อีเมลที่ถูกต้อง', hi: 'कृपया एक मान्य ईमेल पता दर्ज करें।' },
  attendeeGateDenied: { en: 'This email isn’t on the attendee list. Please check with your workshop host.', zh: '此邮箱不在参会者名单中。请与研讨会主办方确认。', ja: 'このメールは参加者リストにありません。ワークショップ主催者にご確認ください。', ko: '이 이메일은 참석자 목록에 없습니다. 워크숍 주최자에게 문의하세요.', th: 'อีเมลนี้ไม่อยู่ในรายชื่อผู้เข้าร่วม โปรดตรวจสอบกับผู้จัดเวิร์กช็อป', hi: 'यह ईमेल उपस्थित सूची में नहीं है। कृपया अपने वर्कशॉप होस्ट से जांचें।' },
  workshopNotStartedTitle: { en: 'Workshop access is not open yet', zh: '研讨会尚未开放', ja: 'ワークショップはまだ開始していません', ko: '워크숍 액세스가 아직 열리지 않았습니다', th: 'ยังไม่เปิดให้เข้าเวิร์กช็อป', hi: 'वर्कशॉप एक्सेस अभी खुला नहीं है' },
  workshopNotStartedIntro: { en: 'Access opens on {date}. Please return on or after the start date.', zh: '访问将于 {date} 开放。请在开始日期当天或之后返回。', ja: '{date} にアクセスが開始されます。開始日以降に戻ってください。', ko: '{date}에 액세스가 열립니다. 시작일 당일이나 그 이후에 다시 방문하세요.', th: 'เปิดให้เข้าในวันที่ {date} โปรดกลับมาในหรือหลังวันที่เริ่มต้น', hi: 'एक्सेस {date} को खुलेगा। आरंभ तारीख पर या उसके बाद वापस आएँ।' },
  workshopEndedTitle: { en: 'Workshop access has ended', zh: '研讨会访问已结束', ja: 'ワークショップのアクセスは終了しました', ko: '워크숍 액세스가 종료되었습니다', th: 'สิทธิ์เข้าเวิร์กช็อปสิ้นสุดแล้ว', hi: 'वर्कशॉप एक्सेस समाप्त हो गया है' },
  workshopEndedIntro: { en: 'Access closed after {date}. Contact the workshop host if you still need access.', zh: '访问已于 {date} 结束后关闭。如仍需访问，请联系研讨会主办方。', ja: '{date} の終了後にアクセスが終了しました。引き続きアクセスが必要な場合は主催者に連絡してください。', ko: '{date} 종료 후 액세스가 닫혔습니다. 계속 액세스해야 하면 워크숍 주최자에게 문의하세요.', th: 'ปิดการเข้าถึงหลังสิ้นสุดวันที่ {date} หากยังต้องการเข้า โปรดติดต่อผู้จัดเวิร์กช็อป', hi: '{date} के बाद एक्सेस बंद हो गया। यदि अभी भी एक्सेस चाहिए तो वर्कशॉप होस्ट से संपर्क करें।' },
  workshopWindowUnavailableTitle: { en: 'Workshop schedule unavailable', zh: '研讨会时段不可用', ja: 'ワークショップのスケジュールを利用できません', ko: '워크숍 일정을 사용할 수 없습니다', th: 'ไม่พร้อมใช้งานกำหนดการเวิร์กช็อป', hi: 'वर्कशॉप शेड्यूल उपलब्ध नहीं है' },
  workshopWindowUnavailableIntro: { en: 'The workshop host needs to correct the configured start and end dates before participants can enter.', zh: '研讨会主办方需要修正已配置的开始与结束日期，参会者才能进入。', ja: '参加者が入場する前に、主催者が開始日と終了日の設定を修正する必要があります。', ko: '참가자가 입장하기 전에 워크숍 주최자가 구성된 시작일과 종료일을 수정해야 합니다.', th: 'ผู้จัดเวิร์กช็อปต้องแก้ไขวันที่เริ่มต้นและสิ้นสุดที่กำหนดไว้ก่อนที่ผู้เข้าร่วมจะเข้าได้', hi: 'प्रतिभागियों के प्रवेश से पहले वर्कशॉप होस्ट को कॉन्फ़िगर की गई आरंभ और समाप्ति तारीखें ठीक करनी होंगी।' },
} satisfies Record<string, LocalizedText>

const vietnameseUi = {
  program: 'AI Agent Workshop by Microsoft Agent GBB',
  kicker: 'Lộ trình học thực hành',
  progress: 'Tiến độ tổng thể',
  lab: 'Bài thực hành',
  minutes: 'phút',
  objectives: 'Mục tiêu học tập',
  prerequisites: 'Trước khi bắt đầu',
  outcome: 'Bạn sẽ xây dựng',
  step: 'Bước',
  highlight: 'Điểm nổi bật',
  input: 'Nội dung đầu vào',
  copy: 'Sao chép',
  copied: 'Đã sao chép',
  expand: 'Mở rộng nội dung',
  collapse: 'Thu gọn nội dung',
  complete: 'Đánh dấu bước là hoàn tất',
  completed: 'Hoàn tất',
  previous: 'Trước',
  next: 'Tiếp',
  screenshot: 'Vị trí dành cho ảnh chụp màn hình',
  screenshotHint: 'Thay thế tệp này bằng ảnh chụp màn hình sản phẩm đã bản địa hóa.',
  viewFullscreen: 'Xem toàn màn hình',
  closeFullscreen: 'Đóng ảnh toàn màn hình',
  previousScreenshot: 'Ảnh chụp màn hình trước',
  nextScreenshot: 'Ảnh chụp màn hình tiếp theo',
  overview: 'Tổng quan',
  guide: 'Hướng dẫn bài thực hành',
  contents: 'Nội dung bài thực hành',
  page: 'Trang',
  theme: 'Chuyển giao diện màu',
  menu: 'Mở điều hướng bài thực hành',
  close: 'Đóng điều hướng',
  collapseSidebar: 'Thu gọn thanh bên',
  expandSidebar: 'Mở rộng thanh bên',
  language: 'Ngôn ngữ',
  exportPdf: 'Xuất bài thực hành này sang PDF',
  viewLabCredentials: 'Xem thông tin đăng nhập bài thực hành của tôi',
  labCredentialsTitle: 'Thông tin đăng nhập bài thực hành của tôi',
  accessKey: 'Khóa truy cập',
  labCredentialsUnavailable: 'Chưa có thông tin đăng nhập bài thực hành nào được gán cho email này.',
  labDoneTitle: 'Chúc mừng!',
  labDoneMessage: 'Bạn đã hoàn thành bài thực hành này — thật tuyệt vời!',
  labDoneContinue: 'Tiếp tục',
  labDoneStay: 'Ở lại đây một chút',
  allDoneTitle: 'Tuyệt vời!',
  allDoneMessage: 'Đập tay nào! Bạn đã hoàn thành tất cả bài thực hành.',
  feedbackHeading: 'Chia sẻ phản hồi',
  feedbackIntro: 'Chỉ mất chưa đến một phút.',
  feedbackOverall: 'Trải nghiệm tổng thể',
  feedbackEffort: 'Mức độ khó',
  feedbackEffortHint: '1 = dễ · 5 = rất khó',
  feedbackRecommend: 'Sẽ giới thiệu cho người khác',
  feedbackComments: 'Nhận xét',
  feedbackCommentsHint: 'Bạn thích điều gì? Chúng tôi có thể cải thiện điều gì?',
  feedbackSubmit: 'Gửi phản hồi',
  feedbackSkip: 'Để sau',
  feedbackThanks: 'Cảm ơn phản hồi của bạn!',
  workshopBranding: 'Tùy chỉnh thương hiệu hội thảo',
  closeDialog: 'Đóng',
  brandingHint: 'Đặt tên hoặc logo khách hàng để đồng thương hiệu cho JumpStart này. Lưu các hội thảo đã đặt tên để tái sử dụng bất cứ lúc nào.',
  hostName: 'Tên đơn vị tổ chức',
  hostLogoUrl: 'URL logo của đơn vị tổ chức',
  logoUrlHint: 'https:// … (hoặc tải lên bên dưới)',
  uploadHostLogo: 'Tải logo đơn vị tổ chức lên',
  customerName: 'Tên khách hàng',
  customerNameHint: 'ví dụ: Contoso',
  customerLogoUrl: 'URL logo khách hàng',
  uploadCustomerLogo: 'Tải logo khách hàng lên',
  removeLogo: 'Xóa',
  reset: 'Đặt lại',
  saveToHistory: 'Lưu vào lịch sử',
  apply: 'Áp dụng',
  applying: 'Đang áp dụng…',
  brandingPublished: 'Đã áp dụng và xuất bản vào branding.json. Hãy commit và push để mọi người đều thấy.',
  brandingSaveFailed: 'Không thể lưu branding.json. Các thay đổi vẫn còn trong biểu mẫu này; chọn Áp dụng để thử lại.',
  workshopHistory: 'Lịch sử hội thảo',
  searchWorkshops: 'Tìm nhanh hội thảo đã lưu…',
  noSavedWorkshops: 'Chưa có hội thảo nào được lưu. Hãy cấu hình thương hiệu ở trên, rồi chọn “Lưu vào lịch sử”.',
  noMatchingWorkshops: 'Không có hội thảo nào khớp với tìm kiếm của bạn.',
  loadWorkshop: 'Tải vào biểu mẫu',
  deleteWorkshop: 'Xóa {name}',
  savedWorkshop: 'Đã lưu “{name}”',
  updatedWorkshop: 'Đã cập nhật “{name}”',
  loadedWorkshop: 'Đã tải “{name}” — chọn Áp dụng để sử dụng',
  maker: 'Chế độ Maker',
  makerUnlock: 'Nhập mật khẩu Maker',
  makerWrong: 'Mật khẩu không đúng',
  reauthHint: 'Phiên Maker của bạn đã hết hạn. Nhập mật khẩu để tiếp tục chỉnh sửa và lưu.',
  unlock: 'Mở khóa',
  exitMaker: 'Thoát chế độ Maker',
  editContent: 'Chỉnh sửa nội dung',
  editingLanguage: 'Ngôn ngữ đang chỉnh sửa',
  copyEnglish: 'Sao chép từ tiếng Anh',
  save: 'Lưu',
  saving: 'Đang lưu…',
  saved: 'Đã lưu',
  publish: 'Xuất bản lên GitHub',
  publishing: 'Đang xuất bản…',
  published: 'Đã xuất bản',
  discard: 'Hủy thay đổi',
  addLab: 'Thêm bài thực hành',
  addStep: 'Thêm bước',
  addPage: 'Thêm trang',
  addParagraph: 'Thêm đoạn văn',
  addObjective: 'Thêm mục tiêu',
  addPrerequisite: 'Thêm điều kiện tiên quyết',
  addImage: 'Thêm khóa ảnh chụp màn hình',
  remove: 'Xóa',
  moveUp: 'Di chuyển lên',
  moveDown: 'Di chuyển xuống',
  labTitle: 'Tiêu đề bài thực hành',
  labSummary: 'Tóm tắt',
  labOutcome: 'Kết quả',
  labIcon: 'Biểu tượng',
  labDuration: 'Thời lượng (phút)',
  labVisibility: 'Phạm vi hiển thị',
  isPublic: 'Công khai',
  isPrivate: 'Riêng tư (chỉ khi build)',
  publicLab: 'Công khai — hiển thị cho người dùng hội thảo sau khi xuất bản và được tính vào tiến độ.',
  privateLab: 'Riêng tư — bản nháp chỉ dùng khi build. Không hiển thị trong hội thảo đã xuất bản và không được tính vào tiến độ.',
  privateBadge: 'Riêng tư',
  cloneStep: 'Nhân bản bước',
  stepVisibility: 'Trạng thái hiển thị của bước',
  stepVisible: 'Hiển thị',
  stepHidden: 'Ẩn',
  stepVisibleHint: 'Hiển thị — người dùng bài thực hành có thể thấy và bước được tính vào tiến độ.',
  stepHiddenHint: 'Ẩn — không xuất hiện trong nội dung đọc, điều hướng và tiến độ của người dùng bài thực hành.',
  stepTitle: 'Tiêu đề bước (Markdown)',
  pageTitle: 'Tiêu đề trang (Markdown, không bắt buộc)',
  fieldHighlight: 'Nội dung nổi bật dạng Markdown (không bắt buộc)',
  fieldPrompt: 'Nội dung đầu vào / prompt (giống nhau cho mọi ngôn ngữ)',
  fieldPromptTitle: 'Tiêu đề đầu vào (ví dụ: Agent instruction, Skill)',
  addPrompt: 'Thêm đầu vào / prompt',
  promptDefaultTitle: 'Hướng dẫn / Đầu vào',
  publishHint: 'Lưu sẽ ghi labs.json cục bộ; Xuất bản sẽ commit và push tệp lên GitHub.',
  fallbackNote: 'Các trường không phải tiếng Anh để trống sẽ dùng tiếng Anh khi học viên xem bài thực hành.',
  preparedByField: 'Người chuẩn bị',
  preparedDateField: 'Ngày chuẩn bị',
  workshopAccessWindow: 'Khoảng thời gian truy cập hội thảo',
  workshopAccessWindowHint: 'Không bắt buộc. Đặt cả hai ngày để cho phép truy cập từ 00:00 ngày bắt đầu đến 23:59:59 ngày kết thúc.',
  workshopStartDate: 'Ngày bắt đầu',
  workshopEndDate: 'Ngày kết thúc',
  workshopWindowInvalid: 'Hãy đặt cả hai ngày và bảo đảm ngày kết thúc trùng hoặc sau ngày bắt đầu.',
  contactsField: 'Cần trợ giúp? Liên hệ',
  contactNameHint: 'Tên (ví dụ: Nguyễn Văn An)',
  contactEmailHint: 'email@microsoft.com',
  addContact: 'Thêm liên hệ',
  removeContact: 'Xóa liên hệ',
  attendeesField: 'Danh sách email người tham dự',
  attendeesHint: 'Không bắt buộc. Khi được thiết lập, người tham dự phải xác minh email trên trang chào mừng trước khi vào bài thực hành. Thêm từng email hoặc dán danh sách được phân tách bằng dấu phẩy / dấu cách / tab.',
  addAttendee: 'Thêm',
  attendeeAddHint: 'name@company.com',
  attendeePasteHint: 'Dán các email được phân tách bằng dấu phẩy, dấu cách, tab hoặc dòng mới…',
  addPastedList: 'Thêm danh sách đã dán',
  clearAll: 'Xóa tất cả',
  removeAttendee: 'Xóa người tham dự',
  attendeesAdded: 'Đã thêm {n}',
  attendeesNoneAdded: 'Không tìm thấy địa chỉ email hợp lệ',
  labUsersField: 'Người dùng bài thực hành và mã truy cập',
  labUsersHint: 'Dán hai cột được sao chép từ Excel. Thông tin đăng nhập này được lưu cùng cấu hình thương hiệu và lần lượt gán lặp lại cho email người tham dự.',
  labUsersPasteHint: 'Dán các cột Excel: tên người dùng bài thực hành    mã truy cập',
  labUserNameColumn: 'Tên người dùng bài thực hành',
  accessCodeColumn: 'Mã truy cập',
  attendeeEmailColumn: 'Email người tham dự',
  addLabUser: 'Thêm hàng',
  labUsersImported: 'Đã nhập {n} người dùng bài thực hành',
  labUsersNoneAdded: 'Không tìm thấy hàng hai cột đầy đủ',
  labUsersIncomplete: 'Mỗi hàng người dùng bài thực hành cần có cả tên người dùng và mã truy cập.',
  generateUserMapping: 'Tạo ánh xạ người dùng',
  generatingUserMapping: 'Đang tạo…',
  userMappingGenerated: 'Đã tải xuống ánh xạ cho {n} người tham dự',
  userMappingFailed: 'Không thể tạo workbook ánh xạ người dùng. Vui lòng thử lại.',
  attendeeGateTitle: 'Xác minh email của bạn',
  attendeeGateIntro: 'Hội thảo này dành cho người tham dự đã đăng ký. Nhập email để tiếp tục.',
  accessWelcomePrompt: 'Nhập email công việc để tiếp tục đến trang chào mừng của hội thảo.',
  attendeeGateLabel: 'Email công việc',
  attendeeGateVerify: 'Xác minh và vào',
  attendeeGateContinue: 'Xác minh và tiếp tục',
  attendeeGateInvalid: 'Vui lòng nhập địa chỉ email hợp lệ.',
  attendeeGateDenied: 'Email này không có trong danh sách người tham dự. Vui lòng kiểm tra với đơn vị tổ chức hội thảo.',
  workshopNotStartedTitle: 'Chưa mở quyền truy cập hội thảo',
  workshopNotStartedIntro: 'Quyền truy cập sẽ mở vào {date}. Vui lòng quay lại vào hoặc sau ngày bắt đầu.',
  workshopEndedTitle: 'Quyền truy cập hội thảo đã kết thúc',
  workshopEndedIntro: 'Quyền truy cập đã đóng sau {date}. Hãy liên hệ đơn vị tổ chức nếu bạn vẫn cần truy cập.',
  workshopWindowUnavailableTitle: 'Không có lịch truy cập hội thảo',
  workshopWindowUnavailableIntro: 'Đơn vị tổ chức cần sửa ngày bắt đầu và ngày kết thúc đã cấu hình trước khi người tham dự có thể vào.',
} satisfies Record<keyof typeof ui, string>

for (const key of Object.keys(vietnameseUi) as Array<keyof typeof ui>) {
  (ui[key] as LocalizedText).vi = vietnameseUi[key]
}

const regionalChineseConverters: Partial<Record<Locale, (value: string) => string>> = {}
const regionalChineseCache = new Map<string, string>()
let regionalChineseLoader: Promise<void> | undefined

export const prepareLocale = (locale: Locale): Promise<void> => {
  if (locale !== 'zh-HK' && locale !== 'zh-TW') return Promise.resolve()
  if (regionalChineseConverters[locale]) return Promise.resolve()

  regionalChineseLoader ??= import('opencc-js/cn2t').then(({ default: OpenCC }) => {
    regionalChineseConverters['zh-HK'] = OpenCC.Converter({ from: 'cn', to: 'hk' })
    regionalChineseConverters['zh-TW'] = OpenCC.Converter({ from: 'cn', to: 'twp' })
  })
  return regionalChineseLoader
}

const regionalChineseText = (value: LocalizedText, locale: Locale): string => {
  const source = value.zh?.trim()
  const converter = regionalChineseConverters[locale]
  if (!source) return ''
  if (!converter) return source

  const cacheKey = `${locale}\u0000${source}`
  const cached = regionalChineseCache.get(cacheKey)
  if (cached) return cached

  const converted = converter(source)
  regionalChineseCache.set(cacheKey, converted)
  return converted
}

export const text = (value: LocalizedText | undefined, locale: Locale): string => {
  if (!value) return ''
  const localized = value[locale]
  if (localized && localized.trim()) return localized
  return regionalChineseText(value, locale) || value.en
}